GET /api/2.4/tenders/d10e6f5566244a1191ba597b97b2f01c/awards/c2383e46f62f4c9d9ed7e60dd7c76073/complaints HTTP/1.0
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "status": "claim", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "complaint_owner", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/62a22f1e64ab46bb9181b3a841eea092?KeyID=57a51152&Signature=xgs2BvShW8UQp7WLgrwJgr63n09g8de5ZAp5rF9JHwo%252B5jFENSI%2F6eUE06gwQoBG%252B6hTVdeADzZ%252BNlKWAlFcAQ%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-08-20T17:05:08.992427+03:00", 
          "id": "f1470aa65cf84130adfe595c0e659b03", 
          "dateModified": "2018-08-20T17:05:08.992445+03:00"
        }
      ], 
      "description": "complaint description", 
      "title": "complaint title", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2018-08-20T17:05:09.172786+03:00", 
      "complaintID": "UA-2018-08-20-000001.5", 
      "date": "2018-08-20T17:05:09.179790+03:00", 
      "type": "claim", 
      "id": "03a6a848b77943c09ba77210e4994fc9"
    }, 
    {
      "status": "claim", 
      "description": "complaint description", 
      "title": "complaint title", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2018-08-20T17:05:09.344015+03:00", 
      "complaintID": "UA-2018-08-20-000001.6", 
      "date": "2018-08-20T17:05:09.344001+03:00", 
      "type": "claim", 
      "id": "df83e80debfb4ff3bb9dd65776d83bc8"
    }
  ]
}

