PATCH /api/2.4/tenders/979269331ffb40a7896036f735600946/awards/9e8aa6d064514d31b946a9319b45aab7/complaints/bb4d7ffdeacb4c20a48e16eff36b0360?acc_token=4247a28adab940b0a9261db1b9235738 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 51
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "resolved", 
    "satisfied": true
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "resolved", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/bbd7d6e597be4ec38a540b9a2119edb1?KeyID=374c28b1&Signature=%252BdoL5OeW6WxYOInxI%2F9so2kUetmfqVxMbt83h8Bc4g6A1vZ%2FtoUMIzEmRApGmQZSc%2FQh7%252BZ9gV3jAFKdiLm5Dg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-21T09:04:35.829624+03:00", 
        "id": "71ab0b463a05448e889359dfcfd133d3", 
        "dateModified": "2018-08-21T09:04:35.829643+03:00"
      }
    ], 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "resolutionType": "resolved", 
    "type": "claim", 
    "title": "complaint title", 
    "satisfied": true, 
    "tendererAction": "Виправлено неконкурентні умови", 
    "dateAnswered": "2018-08-21T09:04:36.530887+03:00", 
    "tendererActionDate": "2018-08-21T09:04:36.530906+03:00", 
    "dateSubmitted": "2018-08-21T09:04:36.007384+03:00", 
    "complaintID": "UA-2018-08-21-000001.5", 
    "date": "2018-08-21T09:04:36.720410+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "bb4d7ffdeacb4c20a48e16eff36b0360"
  }
}

