POST /api/2.4/tenders/d10e6f5566244a1191ba597b97b2f01c/awards/c2383e46f62f4c9d9ed7e60dd7c76073/complaints?acc_token=01d5172c8f084cb58ff33a46b893bb42 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 794
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "claim", 
    "title": "complaint title", 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк", 
        "email": "soleksuk@gmail.com"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "21100", 
        "region": "м. Вінниця", 
        "streetAddress": "вул. Островського, 33", 
        "locality": "м. Вінниця"
      }
    }
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/d10e6f5566244a1191ba597b97b2f01c/awards/c2383e46f62f4c9d9ed7e60dd7c76073/complaints/df83e80debfb4ff3bb9dd65776d83bc8

{
  "access": {
    "token": "38da19a4d506432d89d19cbf0fdc21bf"
  }, 
  "data": {
    "status": "claim", 
    "description": "complaint description", 
    "title": "complaint title", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateSubmitted": "2018-08-20T17:05:09.344015+03:00", 
    "complaintID": "UA-2018-08-20-000001.6", 
    "date": "2018-08-20T17:05:09.344001+03:00", 
    "type": "claim", 
    "id": "df83e80debfb4ff3bb9dd65776d83bc8"
  }
}

