POST /api/2.4/tenders/642d0d9c6f5d4bcaba32a998eb5ceb7a/awards/6a1e8963ef584fc5b02fc13836b6cd1f/complaints?acc_token=5d68d309ef2a45bfa523e11fced5b31e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 794
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "claim", 
    "title": "complaint title", 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк", 
        "email": "soleksuk@gmail.com"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "21100", 
        "region": "м. Вінниця", 
        "streetAddress": "вул. Островського, 33", 
        "locality": "м. Вінниця"
      }
    }
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/642d0d9c6f5d4bcaba32a998eb5ceb7a/awards/6a1e8963ef584fc5b02fc13836b6cd1f/complaints/3db0686ffb3c4b008bf14089803ca24c

{
  "access": {
    "token": "51b8c035ee6149d4a49172d2ab45eda8"
  }, 
  "data": {
    "status": "claim", 
    "description": "complaint description", 
    "title": "complaint title", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateSubmitted": "2018-08-21T08:57:01.167434+03:00", 
    "complaintID": "UA-2018-08-21-000001.6", 
    "date": "2018-08-21T08:57:01.167420+03:00", 
    "type": "claim", 
    "id": "3db0686ffb3c4b008bf14089803ca24c"
  }
}

