PATCH /api/2.4/tenders/979269331ffb40a7896036f735600946/awards/9e8aa6d064514d31b946a9319b45aab7/complaints/b20955e4e58f4d9482bf4a1e1e5930db?acc_token=d70b1b626fac4662a156418ddc1d9a19 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 52
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "resolved", 
    "satisfied": false
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "resolved", 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "satisfied": false, 
    "dateAnswered": "2018-08-21T09:04:36.898132+03:00", 
    "dateSubmitted": "2018-08-21T09:04:36.176828+03:00", 
    "complaintID": "UA-2018-08-21-000001.6", 
    "date": "2018-08-21T09:04:37.087610+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "b20955e4e58f4d9482bf4a1e1e5930db"
  }
}

