PATCH /api/2.4/tenders/afa62c501a20400f9ce1de70f14d5600/awards/5d96a0b16a8a44428a86085028d0b31d/complaints/7c4ef54ff5864ab9a13ecf68a5aceddb?acc_token=6c801217119342a4966296aa7bdec155 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 51
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "resolved", 
    "satisfied": true
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "resolved", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/9b29baa8663240b6ac523c6d6f105e87?KeyID=647466d4&Signature=YECjdzcS%2FdzfFA3X15PCyPgmSxe3%2Fg%2FwbvnkufOiSvs1S4%2F1UyB22se%2Fbmxz944nQHHEX7ihmPAhpOBtbh3QAg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-21T08:56:53.843827+03:00", 
        "id": "2d4fb429f5b74450ae0ddcd7b0f13b38", 
        "dateModified": "2018-08-21T08:56:53.843848+03:00"
      }
    ], 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "resolutionType": "resolved", 
    "type": "claim", 
    "title": "complaint title", 
    "satisfied": true, 
    "tendererAction": "Виправлено неконкурентні умови", 
    "dateAnswered": "2018-08-21T08:56:54.543297+03:00", 
    "tendererActionDate": "2018-08-21T08:56:54.543315+03:00", 
    "dateSubmitted": "2018-08-21T08:56:54.025300+03:00", 
    "complaintID": "UA-2018-08-21-000001.5", 
    "date": "2018-08-21T08:56:54.731110+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "7c4ef54ff5864ab9a13ecf68a5aceddb"
  }
}

