PATCH /api/2.4/tenders/a25c38a278e8492f9d00d36f50173873/awards/8478b70080514e7d8a1c8426262e96e6/complaints/b3935210ce83448ba69e526eeec949ef?acc_token=92b34ebadb604023b3d359f81fa92d72 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 52
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "resolved", 
    "satisfied": false
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "resolved", 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "satisfied": false, 
    "dateAnswered": "2018-08-20T17:16:46.404576+03:00", 
    "dateSubmitted": "2018-08-20T17:16:45.696587+03:00", 
    "complaintID": "UA-2018-08-20-000001.6", 
    "date": "2018-08-20T17:16:46.587813+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "b3935210ce83448ba69e526eeec949ef"
  }
}

