PATCH /api/2.4/tenders/afa62c501a20400f9ce1de70f14d5600/complaints/5644f2faeeb14f0cac1d4190077c0f3b?acc_token=133bba2ff3fb4187a1fa13a3e86e6051 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 442
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "answered", 
    "resolutionType": "resolved", 
    "tendererAction": "Виправлено неконкурентні умови", 
    "resolution": "Виправлено неконкурентні умови"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "answered", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/a17dfc416c714c16bff71e04f35d0a8a?KeyID=647466d4&Signature=MglXSk8NssqEsnnChY4QUaQ3wDxWImJHkzG%252BgSjhYwwC4nonB8dn5XjgOJa7FHN6rk0LSdXC5d%252BixKoYU028Aw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-21T08:56:49.577068+03:00", 
        "id": "50b5cc5ce92745f0b8d1c9c397797a5c", 
        "dateModified": "2018-08-21T08:56:49.577090+03:00"
      }
    ], 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "tendererAction": "Виправлено неконкурентні умови", 
    "dateAnswered": "2018-08-21T08:56:49.998819+03:00", 
    "tendererActionDate": "2018-08-21T08:56:49.998836+03:00", 
    "dateSubmitted": "2018-08-21T08:56:49.709446+03:00", 
    "complaintID": "UA-2018-08-21-000001.1", 
    "date": "2018-08-21T08:56:50.001674+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "5644f2faeeb14f0cac1d4190077c0f3b"
  }
}

