PATCH /api/2.4/tenders/d10e6f5566244a1191ba597b97b2f01c/complaints/2c6620a2fd02415e97795afb0ef267c2?acc_token=2d69d2acd09e490db7178979ebef33fa HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 52
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "resolved", 
    "satisfied": false
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "resolved", 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "satisfied": false, 
    "dateAnswered": "2018-08-20T17:05:05.312409+03:00", 
    "dateSubmitted": "2018-08-20T17:05:04.911447+03:00", 
    "complaintID": "UA-2018-08-20-000001.2", 
    "date": "2018-08-20T17:05:05.447579+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "2c6620a2fd02415e97795afb0ef267c2"
  }
}

