PATCH /api/2.4/tenders/4734a19504774ff2a0f37c62ad04e3aa/complaints/197024c9f0e048feb82da69f7a0fc642?acc_token=26f4abc6a82e4422a4d5a0af96718a7d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 29
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "claim"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "claim", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/463518f2928d451a99b8382002633ad6?KeyID=8fe199b3&Signature=9VliHMEP9%252B2IiXUqkOYVQDE%252BoiFYYMhNYWTd%2Fc3UVOFYLTMJeuUkH5LoGhl4QijV5O0Fjk9Nhbm%2FF6b3PrXUDg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-21T09:04:25.985683+03:00", 
        "id": "c4b0cddefeda40b69fbe34168a8bbc67", 
        "dateModified": "2018-08-21T09:04:25.985703+03:00"
      }
    ], 
    "description": "complaint description", 
    "title": "complaint title", 
    "dateSubmitted": "2018-08-21T09:04:26.113060+03:00", 
    "complaintID": "UA-2018-08-21-000001.1", 
    "date": "2018-08-21T09:04:26.115500+03:00", 
    "type": "claim", 
    "id": "197024c9f0e048feb82da69f7a0fc642"
  }
}

