PATCH /api/2.4/tenders/4734a19504774ff2a0f37c62ad04e3aa/complaints/5ca982c8abf2458c8efb471e5b5d059d?acc_token=e78da01e30cf417687664a1d02eaee8a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 52
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "resolved", 
    "satisfied": false
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "resolved", 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "satisfied": false, 
    "dateAnswered": "2018-08-21T09:04:26.633019+03:00", 
    "dateSubmitted": "2018-08-21T09:04:26.238998+03:00", 
    "complaintID": "UA-2018-08-21-000001.2", 
    "date": "2018-08-21T09:04:26.763182+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "5ca982c8abf2458c8efb471e5b5d059d"
  }
}

