POST /api/2.4/tenders/a25c38a278e8492f9d00d36f50173873/complaints/205c691103fc40abacf3cd9ba706b981/documents?acc_token=2d3d134196aa46a78db43066f6dfdb94 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 341
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.openprocurement.org/get/ca354799347e40099859f5064e6be821?KeyID=a97e205d&Signature=iETIPyoSwrHX8IEWaAFEbQGy2Y%2Fn5H%2B2ibXLKU4gBCmjJy30rjFm6vewtc77QoFuhOAL5eTma92CRVojnUeuCA%3D%3D", 
    "title": "Complaint_Attachement.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/a25c38a278e8492f9d00d36f50173873/complaints/205c691103fc40abacf3cd9ba706b981/documents/de98f6fb8ecf4f0e891d3fffba806c4f

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "complaint_owner", 
    "title": "Complaint_Attachement.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/ca354799347e40099859f5064e6be821?KeyID=a97e205d&Signature=awEnYY7kRhsdoCbSPS4I%2F5ZynEG5TUh40G3%252BakFvy28ipaYKGFdcNxYqoVKTIwZKKNOf%252BfnGunXF7MxR%2FCKbAg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-08-20T17:16:41.092402+03:00", 
    "id": "de98f6fb8ecf4f0e891d3fffba806c4f", 
    "dateModified": "2018-08-20T17:16:41.092422+03:00"
  }
}

