PATCH /api/2.4/tenders/979269331ffb40a7896036f735600946/complaints/548678198bbb48afb130c73733de12bb?acc_token=39ba2fa346eb4f78a15235102c682c72 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 442
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "answered", 
    "resolutionType": "resolved", 
    "tendererAction": "Виправлено неконкурентні умови", 
    "resolution": "Виправлено неконкурентні умови"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "answered", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/81398a5eebf04aa29206363dfc963711?KeyID=374c28b1&Signature=fdQX1W8MO68FGm%252BlV5C2ajY7vB6Z7lwd2UqO9UPliJOQMSG4KtyBH4mcYswnFLFtIneQpNZ9bgztDlOD54YPAg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-21T09:04:31.593245+03:00", 
        "id": "b09ecf5740434c35a336d467799f0065", 
        "dateModified": "2018-08-21T09:04:31.593267+03:00"
      }
    ], 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "tendererAction": "Виправлено неконкурентні умови", 
    "dateAnswered": "2018-08-21T09:04:32.012689+03:00", 
    "tendererActionDate": "2018-08-21T09:04:32.012707+03:00", 
    "dateSubmitted": "2018-08-21T09:04:31.723568+03:00", 
    "complaintID": "UA-2018-08-21-000001.1", 
    "date": "2018-08-21T09:04:32.015740+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "548678198bbb48afb130c73733de12bb"
  }
}

