PATCH /api/2.4/tenders/a25c38a278e8492f9d00d36f50173873/complaints/feda6f6eca214539b5a7f2654763e7ea?acc_token=e3d73f27553a4c2c94742bc384ceeeec HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 52
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "resolved", 
    "satisfied": false
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "resolved", 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "satisfied": false, 
    "dateAnswered": "2018-08-20T17:16:41.740380+03:00", 
    "dateSubmitted": "2018-08-20T17:16:41.340127+03:00", 
    "complaintID": "UA-2018-08-20-000001.2", 
    "date": "2018-08-20T17:16:41.872188+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "feda6f6eca214539b5a7f2654763e7ea"
  }
}

