PATCH /api/2.4/tenders/642d0d9c6f5d4bcaba32a998eb5ceb7a/complaints/e15afcfb13174f51829ed6dc42358da3?acc_token=a7e4a863c44349b1ba848ad8c1ed19fe HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 51
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "resolved", 
    "satisfied": true
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "resolved", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/67832fff26e24394b65720377db0632e?KeyID=1268fedd&Signature=7x8RmhwXEjGdD5lNrCRwFO5gXzyoedG0LoM5XwQI3Eo%2FutfSP5T0jcsqGHHHoVYO9sew768u0VT27p3JUWYDDA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-21T08:56:56.599489+03:00", 
        "id": "b9be391fa668423a844b1280ab3731cf", 
        "dateModified": "2018-08-21T08:56:56.599510+03:00"
      }
    ], 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "satisfied": true, 
    "tendererAction": "Виправлено неконкурентні умови", 
    "dateAnswered": "2018-08-21T08:56:57.011175+03:00", 
    "tendererActionDate": "2018-08-21T08:56:57.011193+03:00", 
    "dateSubmitted": "2018-08-21T08:56:56.731208+03:00", 
    "complaintID": "UA-2018-08-21-000001.1", 
    "date": "2018-08-21T08:56:57.104533+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "e15afcfb13174f51829ed6dc42358da3"
  }
}

