PATCH /api/2.4/tenders/bacb84789fc0414d8646160f1e0d4e11/cancellations/1ebc85164e494f0fb81c4269430bd771?acc_token=725b3b0b374c467384cb2c4b99c21148 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "title": "Notice.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/265affd06231423d9e5b58f35baa4a9b?KeyID=c13f8414&Signature=DmRZVyNIWDY8lEWwfULxvdNeFps2iKLNYKllsoqIFS067UOhJRQ3OpXslHbaKMvi1solk1noUQezCjWsYOd%252BCg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-20T17:16:53.966788+03:00", 
        "id": "be70017c3e794c6c840628dab26b23d7", 
        "dateModified": "2018-08-20T17:16:53.966807+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "title": "Notice-2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/21f3379c5ba94ae1bdb80212f02b3177?KeyID=c13f8414&Signature=V2%2FJ2ybgGUmd5nTmWj%2Fz0LmwMmUXoCi7TMejasqkwAl7C4ds3M3wZ9Ez146EJH1cGngp5QPTQ94EiPHDbgAKCA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-20T17:16:53.966788+03:00", 
        "id": "be70017c3e794c6c840628dab26b23d7", 
        "dateModified": "2018-08-20T17:16:54.295188+03:00"
      }
    ], 
    "reason": "cancellation reason", 
    "date": "2018-08-20T17:16:54.470175+03:00", 
    "cancellationOf": "tender", 
    "id": "1ebc85164e494f0fb81c4269430bd771"
  }
}

