PATCH /api/2.4/tenders/dfa5782e3b144bdca04e994773308880/cancellations/d854305645644d858ce9c9445b0a950e?acc_token=2a2a8652b1e64846ab5c2de4d0a0a4a8 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "title": "Notice.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/8b73964385614db8b441423144642873?KeyID=40792bba&Signature=vRzb9qZxa34x2oVp%252Bu8Q5VRvDTMPRLdisfiMYk2xeQlf0TgRDYv%2Fp4iJkkuCnbGLFRS1X%2FAHVx5WmBpc6pX7DQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-21T09:04:38.978396+03:00", 
        "id": "b2ccca5685424012931baf9f8e16ad6a", 
        "dateModified": "2018-08-21T09:04:38.978415+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "title": "Notice-2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/77ded96d02f241f6ac7191c4dd342144?KeyID=40792bba&Signature=4KvXg6sVtWGIn%2FVwl8aFTwU1Eaq%2FNn4ZnqLtE9VxcWzHmHk89QrYcBHLwyRgiY%2FI2Wpr9793TGaRVkbh2N2%252BCA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-21T09:04:38.978396+03:00", 
        "id": "b2ccca5685424012931baf9f8e16ad6a", 
        "dateModified": "2018-08-21T09:04:39.244521+03:00"
      }
    ], 
    "reason": "cancellation reason", 
    "date": "2018-08-21T09:04:39.388468+03:00", 
    "cancellationOf": "tender", 
    "id": "d854305645644d858ce9c9445b0a950e"
  }
}

