PATCH /api/2.4/tenders/bacb84789fc0414d8646160f1e0d4e11/questions/bdaed27f74d140b0826bc7e00cefc939?acc_token=725b3b0b374c467384cb2c4b99c21148 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 162
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "dateAnswered": "2018-08-20T17:16:50.530104+03:00", 
    "title": "Калорійність", 
    "date": "2018-08-20T17:16:50.415528+03:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "bdaed27f74d140b0826bc7e00cefc939", 
    "questionOf": "tender"
  }
}

