PATCH /api/2.4/tenders/21c028941810479099b6c304472fa513/questions/ed93104d3dff488bbe388290f99ae446?acc_token=ef5f4af395b94893ab1a36ee38398e9f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 162
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "dateAnswered": "2018-08-21T09:04:41.059795+03:00", 
    "title": "Калорійність", 
    "date": "2018-08-21T09:04:40.942087+03:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "ed93104d3dff488bbe388290f99ae446", 
    "questionOf": "tender"
  }
}

