GET /api/2.4/tenders/bacb84789fc0414d8646160f1e0d4e11 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "procurementMethod": "open", 
    "auctionUrl": "http://auction-sandbox.openprocurement.org/tenders/bacb84789fc0414d8646160f1e0d4e11", 
    "enquiryPeriod": {
      "startDate": "2018-08-06T17:16:33.468317+03:00", 
      "endDate": "2018-08-13T17:16:33.468317+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2018-08-20T17:52:33.468317+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "dateAnswered": "2018-08-20T17:16:50.530104+03:00", 
        "title": "Калорійність", 
        "date": "2018-08-20T17:16:50.415528+03:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "bdaed27f74d140b0826bc7e00cefc939", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "id": "bacb84789fc0414d8646160f1e0d4e11", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "document description modified", 
        "title": "Notice.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/811230d2d37d4a2385a1ebe5d70b6e66?KeyID=c13f8414&Signature=kBLSNpCAzX0Yq0%252BpX01oaeemEtTIorIYkUi6%2FYbsBzwFZpusXSzw7eyPEW96W5nPTjdxH8cel%2Ff3lfexXHTzAQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-20T17:16:49.823355+03:00", 
        "author": "tender_owner", 
        "documentType": "technicalSpecifications", 
        "id": "12e10221098e4ed8a5829d228944dd14", 
        "dateModified": "2018-08-20T17:16:49.823373+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "AwardCriteria.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/88755672e52448c9b63e5a52a0819b48?KeyID=c13f8414&Signature=AkUBnfjX03tyd0b1xjICPpDgf6ENCDTbRGpl3JDbAtsIYNP%2Fc3qD87N%252BvU5MIYoDoF1I66yWPEzxnxN%2FOvP%252BDw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-20T17:16:50.162578+03:00", 
        "id": "c08bc208b94e446bb5f72be5978fb939", 
        "dateModified": "2018-08-20T17:16:50.162597+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/e95d73950bf547eb942a58dd34453a6b?KeyID=c13f8414&Signature=PflfKbRsdhbIP%2FzoN84zB2nwRGhkVABBWzqWz7KiRR%252BheVfXq67%2FfgmAqxeq5oyR3JqsGvpoybqN0rEqbQJeCw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-20T17:16:50.162578+03:00", 
        "id": "c08bc208b94e446bb5f72be5978fb939", 
        "dateModified": "2018-08-20T17:16:50.286501+03:00"
      }
    ], 
    "title": "футляри до державних нагород", 
    "tenderID": "UA-2018-08-20-000001", 
    "dateModified": "2018-08-20T17:16:51.547014+03:00", 
    "status": "active.auction", 
    "tenderPeriod": {
      "startDate": "2018-08-13T17:16:33.468317+03:00", 
      "endDate": "2018-08-20T17:16:33.468317+03:00"
    }, 
    "auctionPeriod": {
      "startDate": "2018-08-20T17:16:33.468317+03:00", 
      "shouldStartAfter": "2018-08-21T00:00:00+03:00"
    }, 
    "procurementMethodType": "belowThreshold", 
    "date": "2018-08-20T17:16:48.982661+03:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-08-22T17:16:33.468317+03:00", 
          "endDate": "2018-08-25T17:16:33.468317+03:00"
        }, 
        "id": "04e4ef5c58224d738ee5426a982800bd", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

