GET /api/2.4/tenders/dfa5782e3b144bdca04e994773308880 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "procurementMethod": "open", 
    "mainProcurementCategory": "goods", 
    "auctionUrl": "http://auction-sandbox.openprocurement.org/tenders/dfa5782e3b144bdca04e994773308880", 
    "enquiryPeriod": {
      "startDate": "2018-08-07T09:04:18.465386+03:00", 
      "endDate": "2018-08-14T09:04:18.465386+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2018-08-21T09:40:18.465386+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "dateAnswered": "2018-08-21T09:04:35.440095+03:00", 
        "title": "Калорійність", 
        "date": "2018-08-21T09:04:35.321390+03:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "b73a3c5318ba473c93c03eccb4157c6d", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "id": "dfa5782e3b144bdca04e994773308880", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "document description modified", 
        "title": "Notice.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/16c382c5ad904bd9bd58fec00a0ce980?KeyID=40792bba&Signature=JFvVl3mTelR9KynP8bFbFTY7HYF8K2kWGagJJ6nI6yJgV1hf2vFjmp8VVWKZ4VUshb2dQjXBrG8KSanJ0XJfDA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-21T09:04:34.723834+03:00", 
        "author": "tender_owner", 
        "documentType": "technicalSpecifications", 
        "id": "c1317beaf9db4404ab47de1875038581", 
        "dateModified": "2018-08-21T09:04:34.723853+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "AwardCriteria.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/f3903d64ba1946a6b0472c5f17468e0d?KeyID=40792bba&Signature=g%2FLYBfRirbh5pcZ5rpHC6j3hISLOGdmqi0pi1%2FUEs1BCpjAYJkkkJu%252BOCfVA6ptGoaK7b%252BjD2r0J4r3ETpzSDQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-21T09:04:35.063836+03:00", 
        "id": "c498da6388cb42c5ae35dc63f40de192", 
        "dateModified": "2018-08-21T09:04:35.063856+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/1a92d579090d4f4dbd90e56fe4a0b0aa?KeyID=40792bba&Signature=2xJ81HTcbjR4tNeOnoOizP4RUIB1P%2FsZ7AvmEHFVP5VAkNzWk9SXyf0GONoM75NhtZuG0BBQxN96MPQRHgoVDg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-21T09:04:35.063836+03:00", 
        "id": "c498da6388cb42c5ae35dc63f40de192", 
        "dateModified": "2018-08-21T09:04:35.192767+03:00"
      }
    ], 
    "title": "футляри до державних нагород", 
    "tenderID": "UA-2018-08-21-000001", 
    "dateModified": "2018-08-21T09:04:36.527763+03:00", 
    "status": "active.auction", 
    "tenderPeriod": {
      "startDate": "2018-08-14T09:04:18.465386+03:00", 
      "endDate": "2018-08-21T09:04:18.465386+03:00"
    }, 
    "auctionPeriod": {
      "startDate": "2018-08-21T09:04:18.465386+03:00", 
      "shouldStartAfter": "2018-08-22T00:00:00+03:00"
    }, 
    "procurementMethodType": "belowThreshold", 
    "date": "2018-08-21T09:04:33.946514+03:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-08-23T09:04:18.465386+03:00", 
          "endDate": "2018-08-26T09:04:18.465386+03:00"
        }, 
        "id": "f79b3f40f536402987abc3b3e8d73079", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

