GET /api/2.4/tenders/dfa5782e3b144bdca04e994773308880/bids/3a60470a3c7e4744af35ac8ec8be68f0?acc_token=356561ea2b8344a7adf876d66d05ed1f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/dfa5782e3b144bdca04e994773308880/bids/3a60470a3c7e4744af35ac8ec8be68f0/documents/39b8ed8bcf32436683bc47819d82b33e?download=feb69701ba504f5f81f9e06fe13c0bc8", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-21T09:04:35.907514+03:00", 
        "id": "39b8ed8bcf32436683bc47819d82b33e", 
        "dateModified": "2018-08-21T09:04:35.907532+03:00"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2018-08-21T09:04:35.694832+03:00", 
    "id": "3a60470a3c7e4744af35ac8ec8be68f0", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/dfa5782e3b144bdca04e994773308880?key_for_bid=3a60470a3c7e4744af35ac8ec8be68f0"
  }
}

