GET /api/2.4/tenders/21c028941810479099b6c304472fa513/bids/943a7f30256b4416a04485af1b2a367a?acc_token=1b9c7de1aef1400cab8cf76ac1d7cc2f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/21c028941810479099b6c304472fa513/bids/943a7f30256b4416a04485af1b2a367a/documents/f943a1b4992749d0bf99ca22270de3c4?download=f8bdccf3057b46aba4bd50bd284c36de", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-21T09:04:41.527945+03:00", 
        "id": "f943a1b4992749d0bf99ca22270de3c4", 
        "dateModified": "2018-08-21T09:04:41.527964+03:00"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2018-08-21T09:04:41.316057+03:00", 
    "id": "943a7f30256b4416a04485af1b2a367a", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/21c028941810479099b6c304472fa513?key_for_bid=943a7f30256b4416a04485af1b2a367a"
  }
}

