GET /api/2.4/tenders/0633c141631a4e08aaa96f287e00c8eb/bids/d62b33a0867a4975b2036a6bd9a45fd6?acc_token=ddc3d1343caf4a78a39c052f1655a80f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal_part1.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/0633c141631a4e08aaa96f287e00c8eb/bids/d62b33a0867a4975b2036a6bd9a45fd6/documents/4a9210952e0e4fa5bddf5b55b0e20986?download=27830613fcc342c39a6b572216958244", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-21T08:57:00.013861+03:00", 
        "id": "4a9210952e0e4fa5bddf5b55b0e20986", 
        "dateModified": "2018-08-21T08:57:00.013879+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal_part2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/0633c141631a4e08aaa96f287e00c8eb/bids/d62b33a0867a4975b2036a6bd9a45fd6/documents/4d18e4c4175b49f39608ea2c69ce8aad?download=0e8b19c2078a4566b1b095d338fe4744", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-21T08:57:00.014387+03:00", 
        "id": "4d18e4c4175b49f39608ea2c69ce8aad", 
        "dateModified": "2018-08-21T08:57:00.014405+03:00"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2018-08-21T08:57:00.013225+03:00", 
    "id": "d62b33a0867a4975b2036a6bd9a45fd6", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/0633c141631a4e08aaa96f287e00c8eb?key_for_bid=d62b33a0867a4975b2036a6bd9a45fd6"
  }
}

