GET /api/2.4/tenders/bacb84789fc0414d8646160f1e0d4e11/bids/2dc0c3f54e5d4ed08f8f51fdbbb0cb69?acc_token=6aef1cc88fd14e7eb9eb727e5578fc37 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/bacb84789fc0414d8646160f1e0d4e11/bids/2dc0c3f54e5d4ed08f8f51fdbbb0cb69/documents/0f8e381be6f04ddcb1b26b397950b63c?download=f323c18cc7f74befa6a7eebbb538ecc5", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-20T17:16:51.018560+03:00", 
        "id": "0f8e381be6f04ddcb1b26b397950b63c", 
        "dateModified": "2018-08-20T17:16:51.018579+03:00"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2018-08-20T17:16:50.774965+03:00", 
    "id": "2dc0c3f54e5d4ed08f8f51fdbbb0cb69", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/bacb84789fc0414d8646160f1e0d4e11?key_for_bid=2dc0c3f54e5d4ed08f8f51fdbbb0cb69"
  }
}

