PATCH /api/2.4/tenders/dfa5782e3b144bdca04e994773308880/awards/dbac011a710949c490f06b90bd11bc22?acc_token=2a2a8652b1e64846ab5c2de4d0a0a4a8 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "complaintPeriod": {
      "startDate": "2018-08-21T09:04:36.927285+03:00", 
      "endDate": "2018-08-23T09:04:37.108849+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "bid_id": "18487bf8efa74806bdbc36a46bfb73ea", 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-08-21T09:04:37.113406+03:00", 
    "id": "dbac011a710949c490f06b90bd11bc22"
  }
}

