GET /api/2.4/tenders/0633c141631a4e08aaa96f287e00c8eb/questions/33981ac77f9a41439ce8bf55bd9cee78 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "dateAnswered": "2018-08-21T08:56:59.038902+03:00", 
    "title": "Калорійність", 
    "date": "2018-08-21T08:56:58.919912+03:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "33981ac77f9a41439ce8bf55bd9cee78", 
    "questionOf": "tender"
  }
}

