GET /api/2.4/tenders/dfa5782e3b144bdca04e994773308880/questions/b73a3c5318ba473c93c03eccb4157c6d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "dateAnswered": "2018-08-21T09:04:35.440095+03:00", 
    "title": "Калорійність", 
    "date": "2018-08-21T09:04:35.321390+03:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "b73a3c5318ba473c93c03eccb4157c6d", 
    "questionOf": "tender"
  }
}

