GET /api/2.4/tenders/14bc162d0f5e4538bbf47b0256e2c6b5/questions/57ecb791d63f455a9017431cf226858a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "dateAnswered": "2018-08-21T08:57:05.992487+03:00", 
    "title": "Калорійність", 
    "date": "2018-08-21T08:57:05.868726+03:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "57ecb791d63f455a9017431cf226858a", 
    "questionOf": "tender"
  }
}

