PATCH /api/2.4/tenders/0633c141631a4e08aaa96f287e00c8eb/cancellations/f3885418865c4a3d92470769425743d0/documents/db20bfc9df76483f8d024ade7517cd9d?acc_token=754c3bd1013c4f4fae25583e9d7df5fe HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 48
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "description": "Changed description"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "title": "Notice.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/6cea76424a1a4f57baf652542ee21561?KeyID=0adfe2d1&Signature=oHCEH4J7EwKWVEHV1Nb206TatTSRCq0EozwpYZQtJlEdFjVrjQCfrFXPhlKLN7FrNnHUoZv%252BHZePAnV9i1ykAw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-08-21T08:57:02.785552+03:00", 
    "id": "db20bfc9df76483f8d024ade7517cd9d", 
    "dateModified": "2018-08-21T08:57:02.785573+03:00"
  }
}

