PATCH /api/2.4/tenders/dfa5782e3b144bdca04e994773308880/cancellations/d854305645644d858ce9c9445b0a950e/documents/b2ccca5685424012931baf9f8e16ad6a?acc_token=2a2a8652b1e64846ab5c2de4d0a0a4a8 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 48
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "description": "Changed description"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "title": "Notice.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/8b73964385614db8b441423144642873?KeyID=40792bba&Signature=vRzb9qZxa34x2oVp%252Bu8Q5VRvDTMPRLdisfiMYk2xeQlf0TgRDYv%2Fp4iJkkuCnbGLFRS1X%2FAHVx5WmBpc6pX7DQ%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-08-21T09:04:38.978396+03:00", 
    "id": "b2ccca5685424012931baf9f8e16ad6a", 
    "dateModified": "2018-08-21T09:04:38.978415+03:00"
  }
}

