PATCH /api/2.4/tenders/bd895d3da2ba4b7da4e8909106eed4e4/cancellations/17c7d42a8b554ba69d27ddfd2a753ecc/documents/17023e4f0b684642b0c13e1a5bbed326?acc_token=1d0e92eeafee4e0282182542158f419a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 48
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "description": "Changed description"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "title": "Notice.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/f4be80f5d0d84f91ab31ec2ad5a8dc65?KeyID=16711276&Signature=lrKiCNbfMBYN1ktnjLbzXW1UtZFE6%252BMV0QXM7gwSdNHExfYtafZBSdfShKamTRN%252Bgw1vLVn6AysFSbCqzmsPBw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-08-20T17:05:17.735545+03:00", 
    "id": "17023e4f0b684642b0c13e1a5bbed326", 
    "dateModified": "2018-08-20T17:05:17.735564+03:00"
  }
}

