POST /api/2.4/tenders/14bc162d0f5e4538bbf47b0256e2c6b5/cancellations?acc_token=f52bf8d4a9064d39a19f0eb610aa5f24 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "reason": "cancellation reason"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/14bc162d0f5e4538bbf47b0256e2c6b5/cancellations/817d042af91048b3b81ecc4eae9d2c42

{
  "data": {
    "date": "2018-08-21T08:57:09.331506+03:00", 
    "status": "pending", 
    "reason": "cancellation reason", 
    "cancellationOf": "tender", 
    "id": "817d042af91048b3b81ecc4eae9d2c42"
  }
}

