POST /api/2.4/tenders/bacb84789fc0414d8646160f1e0d4e11/cancellations?acc_token=725b3b0b374c467384cb2c4b99c21148 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "reason": "cancellation reason"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/bacb84789fc0414d8646160f1e0d4e11/cancellations/1ebc85164e494f0fb81c4269430bd771

{
  "data": {
    "date": "2018-08-20T17:16:53.842079+03:00", 
    "status": "pending", 
    "reason": "cancellation reason", 
    "cancellationOf": "tender", 
    "id": "1ebc85164e494f0fb81c4269430bd771"
  }
}

