POST /api/2.4/tenders/bd895d3da2ba4b7da4e8909106eed4e4/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1383
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "documents": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/f3076f74a5e34a5487e46dbbf7140c6b?KeyID=16711276&Signature=k2ggXjOpE%2BahulWbbqh29vhWgtT%2FTzvAdMeZvLJciemr%2BcZIa%2B9G7MTMD%2FBYEo9hOpniGjaSTxChkc5FqcSrCg%3D%3D", 
        "title": "Proposal_part1.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }, 
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/ed4892817f644a47b5ef06b213b2ef46?KeyID=16711276&Signature=UGQH2OC3%2FHOdA%2BdFY%2F6nkGKkw%2F8kdH%2FmYxIKMuwVbg8iOaZRXiRDedH7G3lG8DySOB797ukWZhZnfF9ibSs0BQ%3D%3D", 
        "title": "Proposal_part2.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ], 
    "value": {
      "amount": 499
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк", 
          "email": "aagt@gmail.com"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Львів", 
          "streetAddress": "вул. Островського, 34", 
          "locality": "м. Львів"
        }
      }
    ]
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/bd895d3da2ba4b7da4e8909106eed4e4/bids/e9bd588befb14b67a42abcb88e16bb51

{
  "access": {
    "token": "cf4132aca0e4452781da2ef6fe925e4b"
  }, 
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal_part1.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/bd895d3da2ba4b7da4e8909106eed4e4/bids/e9bd588befb14b67a42abcb88e16bb51/documents/1cb8457e931b434e80b653e369ecd755?download=f3076f74a5e34a5487e46dbbf7140c6b", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-20T17:05:14.916866+03:00", 
        "id": "1cb8457e931b434e80b653e369ecd755", 
        "dateModified": "2018-08-20T17:05:14.916882+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal_part2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/bd895d3da2ba4b7da4e8909106eed4e4/bids/e9bd588befb14b67a42abcb88e16bb51/documents/1316b051352b458d882593eac0f883fa?download=ed4892817f644a47b5ef06b213b2ef46", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-20T17:05:14.917385+03:00", 
        "id": "1316b051352b458d882593eac0f883fa", 
        "dateModified": "2018-08-20T17:05:14.917401+03:00"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2018-08-20T17:05:14.916228+03:00", 
    "id": "e9bd588befb14b67a42abcb88e16bb51"
  }
}

