POST /api/2.4/tenders/bacb84789fc0414d8646160f1e0d4e11/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1369
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "documents": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/0bb4b2acb1ba4053965837f1a7481a82?KeyID=c13f8414&Signature=RklYKhVt81Sv%2B2RknLVgV3y1I32zw1uSxqs5F9oYcKxG6ADuxvTClt4gDPA7KPU5yhwXZchgwnaudOVNjZ9eBQ%3D%3D", 
        "title": "Proposal_part1.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }, 
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/7f573074467b44a78691a0e757c902aa?KeyID=c13f8414&Signature=8AFy9fTpjHGWtvUHLUhChCjnTzOrP8UWx9XsgsXl0XxmklAtgbgf%2FWWfOem%2BNIKBERJsQGeP71lsTqFbbKbVCw%3D%3D", 
        "title": "Proposal_part2.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ], 
    "value": {
      "amount": 499
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк", 
          "email": "aagt@gmail.com"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Львів", 
          "streetAddress": "вул. Островського, 34", 
          "locality": "м. Львів"
        }
      }
    ]
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/bacb84789fc0414d8646160f1e0d4e11/bids/a23d2da5a242419e95de2afd84ff1ae7

{
  "access": {
    "token": "18c28006fffd48ae895e0712c1775209"
  }, 
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal_part1.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/bacb84789fc0414d8646160f1e0d4e11/bids/a23d2da5a242419e95de2afd84ff1ae7/documents/58ffdf71a54845abaf95565dc5a21559?download=0bb4b2acb1ba4053965837f1a7481a82", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-20T17:16:51.201060+03:00", 
        "id": "58ffdf71a54845abaf95565dc5a21559", 
        "dateModified": "2018-08-20T17:16:51.201077+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal_part2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/bacb84789fc0414d8646160f1e0d4e11/bids/a23d2da5a242419e95de2afd84ff1ae7/documents/ae6d034e5f784a0e8301760596936e5a?download=7f573074467b44a78691a0e757c902aa", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-20T17:16:51.201546+03:00", 
        "id": "ae6d034e5f784a0e8301760596936e5a", 
        "dateModified": "2018-08-20T17:16:51.201561+03:00"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2018-08-20T17:16:51.200426+03:00", 
    "id": "a23d2da5a242419e95de2afd84ff1ae7"
  }
}

