POST /api/2.4/tenders/21c028941810479099b6c304472fa513/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1373
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "documents": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/316c6917881e46199e53225d5f8207c5?KeyID=26fd9873&Signature=PhAzhEB8Pg%2FKOHVjo80SQWeJXKFVy3fg%2FHO%2F3kNtFR8LyO1PQNkWoxl9Vf76dfjBS7dqsT9Tox1L9Kw9Wi8ICg%3D%3D", 
        "title": "Proposal_part1.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }, 
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/97c16ecbcc8a47c380262a86cb80c4ac?KeyID=26fd9873&Signature=xll%2FO7ET4vS5a2nfpL6haj%2FmqXNWv4GK9aKMyHh3ZO5Z4Fd16D9TIT7qTgUKOCumYo3JrWmi4rTtNciuKNCmAQ%3D%3D", 
        "title": "Proposal_part2.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ], 
    "value": {
      "amount": 499
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк", 
          "email": "aagt@gmail.com"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Львів", 
          "streetAddress": "вул. Островського, 34", 
          "locality": "м. Львів"
        }
      }
    ]
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/21c028941810479099b6c304472fa513/bids/c8034d0baff643e083dcf63579777907

{
  "access": {
    "token": "2a59fae0af424072916a38aa2dc9727c"
  }, 
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal_part1.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/21c028941810479099b6c304472fa513/bids/c8034d0baff643e083dcf63579777907/documents/25ce52f86c1544d2982d3c804f6cf10d?download=316c6917881e46199e53225d5f8207c5", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-21T09:04:41.719409+03:00", 
        "id": "25ce52f86c1544d2982d3c804f6cf10d", 
        "dateModified": "2018-08-21T09:04:41.719425+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal_part2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/21c028941810479099b6c304472fa513/bids/c8034d0baff643e083dcf63579777907/documents/5ec5c63024904ae285b15b5a70368591?download=97c16ecbcc8a47c380262a86cb80c4ac", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-21T09:04:41.719950+03:00", 
        "id": "5ec5c63024904ae285b15b5a70368591", 
        "dateModified": "2018-08-21T09:04:41.719966+03:00"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2018-08-21T09:04:41.718763+03:00", 
    "id": "c8034d0baff643e083dcf63579777907"
  }
}

