GET /api/2.4/tenders?mode=__all__ HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "next_page": {
    "path": "/api/2.4/tenders?offset=2018-08-21T08%3A57%3A04.463495%2B03%3A00", 
    "uri": "http://api-sandbox.openprocurement.org/api/2.4/tenders?offset=2018-08-21T08%3A57%3A04.463495%2B03%3A00", 
    "offset": "2018-08-21T08:57:04.463495+03:00"
  }, 
  "data": [
    {
      "id": "14bc162d0f5e4538bbf47b0256e2c6b5", 
      "dateModified": "2018-08-21T08:57:04.463495+03:00"
    }
  ]
}

