PATCH /api/2.4/tenders/bacb84789fc0414d8646160f1e0d4e11/documents/12e10221098e4ed8a5829d228944dd14?acc_token=725b3b0b374c467384cb2c4b99c21148 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 58
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "description": "document description modified"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "document description modified", 
    "title": "Notice.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/811230d2d37d4a2385a1ebe5d70b6e66?KeyID=c13f8414&Signature=kBLSNpCAzX0Yq0%252BpX01oaeemEtTIorIYkUi6%2FYbsBzwFZpusXSzw7eyPEW96W5nPTjdxH8cel%2Ff3lfexXHTzAQ%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-08-20T17:16:49.823355+03:00", 
    "author": "tender_owner", 
    "documentType": "technicalSpecifications", 
    "id": "12e10221098e4ed8a5829d228944dd14", 
    "dateModified": "2018-08-20T17:16:49.823373+03:00"
  }
}

