PATCH /api/2.4/tenders/dfa5782e3b144bdca04e994773308880/documents/c1317beaf9db4404ab47de1875038581?acc_token=2a2a8652b1e64846ab5c2de4d0a0a4a8 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 53
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "documentType": "technicalSpecifications"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "Notice.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/16c382c5ad904bd9bd58fec00a0ce980?KeyID=40792bba&Signature=JFvVl3mTelR9KynP8bFbFTY7HYF8K2kWGagJJ6nI6yJgV1hf2vFjmp8VVWKZ4VUshb2dQjXBrG8KSanJ0XJfDA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-08-21T09:04:34.723834+03:00", 
    "documentType": "technicalSpecifications", 
    "id": "c1317beaf9db4404ab47de1875038581", 
    "dateModified": "2018-08-21T09:04:34.723853+03:00"
  }
}

