POST /api/2.4/tenders/14bc162d0f5e4538bbf47b0256e2c6b5/contracts/c6dec65a2daa4ddd98587e27afa5a9da/documents?acc_token=f52bf8d4a9064d39a19f0eb610aa5f24 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 351
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.openprocurement.org/get/659b59b5b36643b381229a8b98b3bab9?KeyID=b6d7061b&Signature=3o%2F97nm3nDL9VvrGGLJyGDhDtjn2QDJ6xx1oHA8LsYWFt0wHszhO1s%2BgWNGqC50B%2B0KO5qYqhP%2F5tULfh77dDw%3D%3D", 
    "title": "contract_second_document.doc", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/msword"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/14bc162d0f5e4538bbf47b0256e2c6b5/contracts/c6dec65a2daa4ddd98587e27afa5a9da/documents/4836b5f1d24c41f9ba05257b326e7175

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "contract_second_document.doc", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/659b59b5b36643b381229a8b98b3bab9?KeyID=b6d7061b&Signature=K6UIQdyIFUg8V8dQLv8lI8pfkLrAeJiaebB3%252BlSmQDD1T3Fxq%2F2s3nkkJCZC99j1YpYwU%2F%2FS32hDrjbilWX%2FDg%253D%253D", 
    "format": "application/msword", 
    "documentOf": "tender", 
    "datePublished": "2018-08-21T08:57:08.598950+03:00", 
    "id": "4836b5f1d24c41f9ba05257b326e7175", 
    "dateModified": "2018-08-21T08:57:08.598969+03:00"
  }
}

