GET /api/2.4/tenders/21c028941810479099b6c304472fa513/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "document description modified", 
      "title": "Notice.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/d4a822c55fe64820a6a148d9d232e680?KeyID=26fd9873&Signature=0t6qV5o0%252BnXDHnkA5SLq%252BFs6RQt8vvvhMl8bS3RbJhRAnU9CZv6QdII4f%252BpxMpIIoTlXs9vongZlY4FHozxaDw%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2018-08-21T09:04:40.348812+03:00", 
      "author": "tender_owner", 
      "documentType": "technicalSpecifications", 
      "id": "95a6800537724de6a9aabff4b6694dd1", 
      "dateModified": "2018-08-21T09:04:40.348833+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "title": "AwardCriteria-2.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/b59682c5f66e45779db3063ffe0305da?KeyID=26fd9873&Signature=GY9UNwbJXT1C%2FmuglrDWQ1BoiXRiIcAZ04G9app5pV7s%252B07T2izKK4vjVypAeS21305JUraGekZ9kzvv8WnZBw%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2018-08-21T09:04:40.688726+03:00", 
      "id": "0f33e002d3524589b4ecfd2c2fa52174", 
      "dateModified": "2018-08-21T09:04:40.814036+03:00"
    }
  ]
}

