PATCH /api/2.4/tenders/c0c71b58dbf44ad2acbbcd0445efdc66?acc_token=8297d2703fc34093ace0b767c0fe2388 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 40
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active.enquiries"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "procurementMethod": "open", 
    "status": "active.enquiries", 
    "mainProcurementCategory": "goods", 
    "tenderPeriod": {
      "startDate": "2018-08-28T08:56:41.953262+03:00", 
      "endDate": "2018-09-04T08:56:41.953262+03:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-08-23T08:56:41.953262+03:00", 
          "endDate": "2018-08-26T08:56:41.953262+03:00"
        }, 
        "id": "0f77560eca1b4278abdf3807d78cb187", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "procurementMethodType": "belowThreshold", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "date": "2018-08-21T08:56:48.207138+03:00", 
    "next_check": "2018-08-28T08:56:41.953262+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "awardCriteria": "lowestCost", 
    "enquiryPeriod": {
      "startDate": "2018-08-21T08:56:48.102368+03:00", 
      "endDate": "2018-08-28T08:56:41.953262+03:00"
    }, 
    "owner": "broker", 
    "dateModified": "2018-08-21T08:56:48.207138+03:00", 
    "id": "c0c71b58dbf44ad2acbbcd0445efdc66", 
    "tenderID": "UA-2018-08-21-000001"
  }
}

