PATCH /api/2.4/tenders/21c028941810479099b6c304472fa513/documents/95a6800537724de6a9aabff4b6694dd1?acc_token=ef5f4af395b94893ab1a36ee38398e9f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 53
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "documentType": "technicalSpecifications"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "Notice.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/d4a822c55fe64820a6a148d9d232e680?KeyID=26fd9873&Signature=0t6qV5o0%252BnXDHnkA5SLq%252BFs6RQt8vvvhMl8bS3RbJhRAnU9CZv6QdII4f%252BpxMpIIoTlXs9vongZlY4FHozxaDw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-08-21T09:04:40.348812+03:00", 
    "documentType": "technicalSpecifications", 
    "id": "95a6800537724de6a9aabff4b6694dd1", 
    "dateModified": "2018-08-21T09:04:40.348833+03:00"
  }
}

