GET /api/2.4/tenders/bd895d3da2ba4b7da4e8909106eed4e4/contracts/9f866bd85d1f4bd785167a1093a0edde/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "title": "contract_first_document.doc", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/baf0cebc31274ec5acd5708613770cfd?KeyID=16711276&Signature=qi0v%252Bh65mZCwC9xyehGUToYhcdHebkuX9pfTOJT1nlaqcAHOsm%2FvsySPAXg89tr3efgN7304cz9V72f%252BqZCQBg%253D%253D", 
      "format": "application/msword", 
      "documentOf": "tender", 
      "datePublished": "2018-08-20T17:05:16.604720+03:00", 
      "id": "60b5949deb9747bb9cb75963e6734171", 
      "dateModified": "2018-08-20T17:05:16.604740+03:00"
    }
  ]
}

