PATCH /api/2.4/tenders/0633c141631a4e08aaa96f287e00c8eb/contracts/44da6c20d3304d4ba65212c792a5df55?acc_token=754c3bd1013c4f4fae25583e9d7df5fe HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 60
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "dateSigned": "2018-08-21T08:57:02.046978+03:00"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "contract_first_document.doc", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/2c6b461b70df454d829c44d8695d266d?KeyID=0adfe2d1&Signature=spTKhTVCjHP1I2D2MlyTs8pbN0uTJBA6iFuy%2FJ4c%252BFOckPonf7T6be1b%2FLx54VsFLFm5et4pZUsXfmh%252B2Dn%252BAg%253D%253D", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2018-08-21T08:57:01.664397+03:00", 
        "id": "36b36fd249b04028b436a8eb685c3f9c", 
        "dateModified": "2018-08-21T08:57:01.664417+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "contract_second_document.doc", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/73cea8ebf73b465ab177f11b26c6f38b?KeyID=0adfe2d1&Signature=y1SgMkaBpjmtUAPzkxyXsXz3Bmncm8wJ1E07jTJwxPN2%2FKACn5rdpnAxhXrdUJ26daBSl1Rc8IjJbFZ1ZgDGCw%253D%253D", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2018-08-21T08:57:01.889854+03:00", 
        "id": "e192bac7182646ccbddca39de1f85255", 
        "dateModified": "2018-08-21T08:57:01.889874+03:00"
      }
    ], 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-08-23T08:56:41.953262+03:00", 
          "endDate": "2018-08-26T08:56:41.953262+03:00"
        }, 
        "id": "3be692b62f0b4f04befe845a12719905", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "contractNumber": "contract #13111", 
    "period": {
      "startDate": "2018-08-21T08:56:41.953395+03:00", 
      "endDate": "2019-08-21T08:56:41.953395+03:00"
    }, 
    "dateSigned": "2018-08-21T08:57:02.046978+03:00", 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-08-21T08:57:00.929131+03:00", 
    "awardID": "8e6e1366b6274d7f9d4c6add02d2d347", 
    "id": "44da6c20d3304d4ba65212c792a5df55", 
    "contractID": "UA-2018-08-21-000001-1"
  }
}

