POST /api/2.4/tenders/dfa5782e3b144bdca04e994773308880/contracts/f30999aa71724b0cb7eadd786ee73f14/documents?acc_token=2a2a8652b1e64846ab5c2de4d0a0a4a8 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 347
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.openprocurement.org/get/079198c07f1e4b6fae22cf05392a1ade?KeyID=40792bba&Signature=0BH6JgiPh2rTRdN103RTNE1oeTzTqiLLwkaspbuc2G%2BGrtcHGwLUUCVx15g%2FzrboG5iKZEoRBxc6WnqmvmU2BQ%3D%3D", 
    "title": "contract_second_document.doc", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/msword"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/dfa5782e3b144bdca04e994773308880/contracts/f30999aa71724b0cb7eadd786ee73f14/documents/be9f49b225c04ac8b4e4bb510086a75e

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "contract_second_document.doc", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/079198c07f1e4b6fae22cf05392a1ade?KeyID=40792bba&Signature=wlrK1kG5nZjEcZKpU0PYWdmQ%252BRDyHupfyI9%2FUOJezhdnpTciRRdBchyz8yvnhauAUuUdUhfRHCNrnTLhLgsVAA%253D%253D", 
    "format": "application/msword", 
    "documentOf": "tender", 
    "datePublished": "2018-08-21T09:04:38.077074+03:00", 
    "id": "be9f49b225c04ac8b4e4bb510086a75e", 
    "dateModified": "2018-08-21T09:04:38.077093+03:00"
  }
}

