POST /api/2.4/tenders/bd895d3da2ba4b7da4e8909106eed4e4/contracts/9f866bd85d1f4bd785167a1093a0edde/documents?acc_token=1d0e92eeafee4e0282182542158f419a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 349
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.openprocurement.org/get/47f4d4abf40349b7b3bbd4bc07f6fcbb?KeyID=16711276&Signature=eiN%2BONj79GxSRwkTydQmJZLRb%2FXZThfdqg9vaa8PpxyDujJJ6%2FD7gIboK2FUKdxpotiyLTy0HZGGypoqyneZBQ%3D%3D", 
    "title": "contract_second_document.doc", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/msword"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/bd895d3da2ba4b7da4e8909106eed4e4/contracts/9f866bd85d1f4bd785167a1093a0edde/documents/e3a503d5aaa940b4adc267fdcf513047

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "contract_second_document.doc", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/47f4d4abf40349b7b3bbd4bc07f6fcbb?KeyID=16711276&Signature=8ypQcDO3Bed3Oh4A0cYxwjfGA24YIRtucA3QfZnwTREYJ7FicowEOuCUKNAiXOkPjAb7U%2Fp8e8qB0ZeVHfmbAg%253D%253D", 
    "format": "application/msword", 
    "documentOf": "tender", 
    "datePublished": "2018-08-20T17:05:16.836029+03:00", 
    "id": "e3a503d5aaa940b4adc267fdcf513047", 
    "dateModified": "2018-08-20T17:05:16.836048+03:00"
  }
}

