PATCH /api/2.4/tenders/bd895d3da2ba4b7da4e8909106eed4e4/contracts/9f866bd85d1f4bd785167a1093a0edde?acc_token=1d0e92eeafee4e0282182542158f419a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "contract_first_document.doc", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/baf0cebc31274ec5acd5708613770cfd?KeyID=16711276&Signature=qi0v%252Bh65mZCwC9xyehGUToYhcdHebkuX9pfTOJT1nlaqcAHOsm%2FvsySPAXg89tr3efgN7304cz9V72f%252BqZCQBg%253D%253D", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2018-08-20T17:05:16.604720+03:00", 
        "id": "60b5949deb9747bb9cb75963e6734171", 
        "dateModified": "2018-08-20T17:05:16.604740+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "contract_second_document.doc", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/47f4d4abf40349b7b3bbd4bc07f6fcbb?KeyID=16711276&Signature=8ypQcDO3Bed3Oh4A0cYxwjfGA24YIRtucA3QfZnwTREYJ7FicowEOuCUKNAiXOkPjAb7U%2Fp8e8qB0ZeVHfmbAg%253D%253D", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2018-08-20T17:05:16.836029+03:00", 
        "id": "e3a503d5aaa940b4adc267fdcf513047", 
        "dateModified": "2018-08-20T17:05:16.836048+03:00"
      }
    ], 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-08-22T17:04:56.722850+03:00", 
          "endDate": "2018-08-25T17:04:56.722850+03:00"
        }, 
        "id": "0897526d1a144ca9a02ad7a9e0bc5df8", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "contractNumber": "contract #13111", 
    "period": {
      "startDate": "2018-08-20T17:04:56.722982+03:00", 
      "endDate": "2019-08-20T17:04:56.722982+03:00"
    }, 
    "dateSigned": "2018-08-20T17:05:16.994036+03:00", 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-08-20T17:05:17.319149+03:00", 
    "awardID": "b2249a626e77442996569aef85d9aa96", 
    "id": "9f866bd85d1f4bd785167a1093a0edde", 
    "contractID": "UA-2018-08-20-000001-1"
  }
}

