GET /api/2.4/tenders/dfa5782e3b144bdca04e994773308880/contracts/f30999aa71724b0cb7eadd786ee73f14/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "title": "contract_first_document.doc", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/9952d18e61664bdcba72a3ca7b6c1054?KeyID=40792bba&Signature=YxyTiFp8vHtKYIvQGwwHK7LCjVgHZzWrVEgiR%252Bktyabe7oEL7F9DrAXBgId4LQOpoZ9o6nF0HSXpD0h8pA6PDQ%253D%253D", 
      "format": "application/msword", 
      "documentOf": "tender", 
      "datePublished": "2018-08-21T09:04:37.852506+03:00", 
      "id": "0b1119b9e8d34607a13a3f3c14657ddd", 
      "dateModified": "2018-08-21T09:04:37.852524+03:00"
    }
  ]
}

