PATCH /api/2.4/tenders/14bc162d0f5e4538bbf47b0256e2c6b5/documents/dc1290bcbc8c45c6862aeb9d1e437f21?acc_token=f52bf8d4a9064d39a19f0eb610aa5f24 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 58
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "description": "document description modified"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "document description modified", 
    "title": "Notice.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/8258bb4dad624c0bb370b3828c369d12?KeyID=b6d7061b&Signature=UztwdgK3jGL3ZORkHP3UBx6J%252BMn1MJvV6eOZnGqFQ2%252BFXcvhfGnmBBbjuIKx5yGpEZUAbSSCd%252BcPef1aauYjCw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-08-21T08:57:05.285877+03:00", 
    "author": "tender_owner", 
    "documentType": "technicalSpecifications", 
    "id": "dc1290bcbc8c45c6862aeb9d1e437f21", 
    "dateModified": "2018-08-21T08:57:05.285896+03:00"
  }
}

