GET /api/2.4/tenders/0633c141631a4e08aaa96f287e00c8eb/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "document description modified", 
      "title": "Notice.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/1ff0b0d4cbe649c3917cec6b42b1a8eb?KeyID=0adfe2d1&Signature=86EXwl89tp9LUMzVoIsZ%2FgAvrkI5lGTd1hpLWXT5cnYzQyZH7TQ12TfNYUByJ7syasf4rMrx3TJfrsd%2FZPUlDA%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2018-08-21T08:56:58.331240+03:00", 
      "author": "tender_owner", 
      "documentType": "technicalSpecifications", 
      "id": "b4b56b63c8c14d459453c5d98ff87450", 
      "dateModified": "2018-08-21T08:56:58.331261+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "title": "AwardCriteria.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/982e6c423a84484082957075a5a0db30?KeyID=0adfe2d1&Signature=kD7tfHGFam8IB7EpzG4cN2E2lAyGmTCXfW42v5HiGZ0BmROJOQif4L3LqLL3EVf3yFH1QjUGqlVCYG43kZRHBQ%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2018-08-21T08:56:58.667184+03:00", 
      "id": "2145309e1e234f4ab434ac4328de0d33", 
      "dateModified": "2018-08-21T08:56:58.667205+03:00"
    }
  ]
}

