PATCH /api/2.4/tenders/14bc162d0f5e4538bbf47b0256e2c6b5/contracts/c6dec65a2daa4ddd98587e27afa5a9da?acc_token=f52bf8d4a9064d39a19f0eb610aa5f24 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "contract_first_document.doc", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/6bcc5fd8a9594f2a9fee259790409b06?KeyID=b6d7061b&Signature=ccU2307L5nTMG5QVHRVIt4I73RxvMmkrVEkKXL%252B8wQZFosImbj9nUAAUijiaBvUqjdOA%252Bv9%252B9DCQmIsvojPhDw%253D%253D", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2018-08-21T08:57:08.370152+03:00", 
        "id": "f1df839cdc754989b2cae6f176daf421", 
        "dateModified": "2018-08-21T08:57:08.370170+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "contract_second_document.doc", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/659b59b5b36643b381229a8b98b3bab9?KeyID=b6d7061b&Signature=K6UIQdyIFUg8V8dQLv8lI8pfkLrAeJiaebB3%252BlSmQDD1T3Fxq%2F2s3nkkJCZC99j1YpYwU%2F%2FS32hDrjbilWX%2FDg%253D%253D", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2018-08-21T08:57:08.598950+03:00", 
        "id": "4836b5f1d24c41f9ba05257b326e7175", 
        "dateModified": "2018-08-21T08:57:08.598969+03:00"
      }
    ], 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-08-23T08:56:49.000134+03:00", 
          "endDate": "2018-08-26T08:56:49.000134+03:00"
        }, 
        "id": "7408ff9344004fd0a7b6cc59cf0c9bb1", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "contractNumber": "contract #13111", 
    "period": {
      "startDate": "2018-08-21T08:56:49.000262+03:00", 
      "endDate": "2019-08-21T08:56:49.000262+03:00"
    }, 
    "dateSigned": "2018-08-21T08:57:08.755804+03:00", 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-08-21T08:57:09.067928+03:00", 
    "awardID": "dfb0aff8a29b4ad68c7aeacf5a3247ea", 
    "id": "c6dec65a2daa4ddd98587e27afa5a9da", 
    "contractID": "UA-2018-08-21-000001-1"
  }
}

