PATCH /api/2.4/tenders/f07ad6d10d364d1ca8afb6d0ed7633f9?acc_token=a8d11f3a23fa44c5b4ab8f21ab80aba4 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 40
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active.enquiries"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "procurementMethod": "open", 
    "status": "active.enquiries", 
    "mainProcurementCategory": "goods", 
    "tenderPeriod": {
      "startDate": "2018-08-27T17:04:56.722850+03:00", 
      "endDate": "2018-09-03T17:04:56.722850+03:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-08-22T17:04:56.722850+03:00", 
          "endDate": "2018-08-25T17:04:56.722850+03:00"
        }, 
        "id": "a2d28210d5d141b6a331ef0472a863af", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "procurementMethodType": "belowThreshold", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "date": "2018-08-20T17:05:03.235390+03:00", 
    "next_check": "2018-08-27T17:04:56.722850+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "awardCriteria": "lowestCost", 
    "enquiryPeriod": {
      "startDate": "2018-08-20T17:05:03.121561+03:00", 
      "endDate": "2018-08-27T17:04:56.722850+03:00"
    }, 
    "owner": "broker", 
    "dateModified": "2018-08-20T17:05:03.235390+03:00", 
    "id": "f07ad6d10d364d1ca8afb6d0ed7633f9", 
    "tenderID": "UA-2018-08-20-000001"
  }
}

