POST /api/2.4/tenders/14bc162d0f5e4538bbf47b0256e2c6b5/contracts/c6dec65a2daa4ddd98587e27afa5a9da/documents?acc_token=f52bf8d4a9064d39a19f0eb610aa5f24 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 342
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.openprocurement.org/get/6bcc5fd8a9594f2a9fee259790409b06?KeyID=b6d7061b&Signature=n4my7v3cK6nOw06CwmswXmupf3qNTbawYdravNBcR3znJVJ7hyNppfUEBVw0uxtS1Jc7yDHNnOa3qz2nOvwMDA%3D%3D", 
    "title": "contract_first_document.doc", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/msword"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/14bc162d0f5e4538bbf47b0256e2c6b5/contracts/c6dec65a2daa4ddd98587e27afa5a9da/documents/f1df839cdc754989b2cae6f176daf421

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "contract_first_document.doc", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/6bcc5fd8a9594f2a9fee259790409b06?KeyID=b6d7061b&Signature=ccU2307L5nTMG5QVHRVIt4I73RxvMmkrVEkKXL%252B8wQZFosImbj9nUAAUijiaBvUqjdOA%252Bv9%252B9DCQmIsvojPhDw%253D%253D", 
    "format": "application/msword", 
    "documentOf": "tender", 
    "datePublished": "2018-08-21T08:57:08.370152+03:00", 
    "id": "f1df839cdc754989b2cae6f176daf421", 
    "dateModified": "2018-08-21T08:57:08.370170+03:00"
  }
}

