PUT /api/2.4/tenders/0633c141631a4e08aaa96f287e00c8eb/cancellations/f3885418865c4a3d92470769425743d0/documents/db20bfc9df76483f8d024ade7517cd9d?acc_token=754c3bd1013c4f4fae25583e9d7df5fe HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 336
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.openprocurement.org/get/0f9ce73bf25d4939880c67ca7c650b5f?KeyID=0adfe2d1&Signature=SfJ%2BCQmUPn%2FHjXjF1siR%2FE3Hho%2FRXWT%2B38qJHZnHUPgCGGPvgUUmzE0WwYNcvZ%2Banxl1bdYVKCvTBNeDsBASDg%3D%3D", 
    "title": "Notice-2.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "title": "Notice-2.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/0f9ce73bf25d4939880c67ca7c650b5f?KeyID=0adfe2d1&Signature=4vsqqgliFjGSXExp9ccse%2FzZt%2FTrzRILJHykC8xeMN588nyr08m19UdM%252BOHc4KyxXQZGtRxbjxFP6e1ZLiJ9Ag%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-08-21T08:57:02.785552+03:00", 
    "id": "db20bfc9df76483f8d024ade7517cd9d", 
    "dateModified": "2018-08-21T08:57:03.044568+03:00"
  }
}

