PUT /api/2.4/tenders/bd895d3da2ba4b7da4e8909106eed4e4/documents/5851d9f2d065433eab9a8d6a928cc478?acc_token=1d0e92eeafee4e0282182542158f419a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 343
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.openprocurement.org/get/146655dd59dd46c988581f529fbd7993?KeyID=16711276&Signature=XV%2F3IZ%2BuB5WDtHU2tPhJF4CIvzLvAxUiQcDuKLo%2F%2B4OcJ2kKw%2BZ2MYdZ1DkDZIpukLIKssOkw1mcN7H%2BFV8kAQ%3D%3D", 
    "title": "AwardCriteria-2.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "AwardCriteria-2.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/146655dd59dd46c988581f529fbd7993?KeyID=16711276&Signature=U9uDP%2FMJSSmK375WAtGDJoAp8iNn3a%2FHVB%252BRGThwDNaSsv45ZoEt4ebA1w2w1HSPBsNeANwoL3lHLFv6FJjtCw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-08-20T17:05:13.881281+03:00", 
    "id": "5851d9f2d065433eab9a8d6a928cc478", 
    "dateModified": "2018-08-20T17:05:14.001660+03:00"
  }
}

