PUT /api/2.4/tenders/21c028941810479099b6c304472fa513/cancellations/fc96ac8b712046a1b4340b8b69f71084/documents/c31b41084aab464fa3ee6cdb33d1bd17?acc_token=ef5f4af395b94893ab1a36ee38398e9f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 330
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.openprocurement.org/get/9e65aa69ac104c218b891748422e9da0?KeyID=26fd9873&Signature=MIdYDieGrYoQFSrGV%2Bvt%2BorNL80oi37bmc1p7DyujCOKGy1CRRCXUFqUdTggSmWbyAFyZ9%2BRrOqixJiYVqeeAQ%3D%3D", 
    "title": "Notice-2.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "title": "Notice-2.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/9e65aa69ac104c218b891748422e9da0?KeyID=26fd9873&Signature=e0UGqB1hWqOrdMi%252Buwr%252B5xINNgMJYuCZjxPQnYGhbY46VEbkeguuTVS5UqjyClktbRJx5EH65R26tsdKHmc1Dw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-08-21T09:04:44.536410+03:00", 
    "id": "c31b41084aab464fa3ee6cdb33d1bd17", 
    "dateModified": "2018-08-21T09:04:44.830052+03:00"
  }
}

