PUT /api/2.4/tenders/bd895d3da2ba4b7da4e8909106eed4e4/cancellations/17c7d42a8b554ba69d27ddfd2a753ecc/documents/17023e4f0b684642b0c13e1a5bbed326?acc_token=1d0e92eeafee4e0282182542158f419a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 326
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.openprocurement.org/get/cafe42532bad4fb08bcf73b7048d9d9e?KeyID=16711276&Signature=LQDYJNGKb235WNl5D4mahkyqNOZZIQWUcgqAne5VNSVSz1TbCtwhB0kwMjPTPx4oRgvUyVsNF9k8idt1%2FjNQAw%3D%3D", 
    "title": "Notice-2.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "title": "Notice-2.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/cafe42532bad4fb08bcf73b7048d9d9e?KeyID=16711276&Signature=OoGWA%252BT9%252BJ2qMpHfjBq50bNgyTVfAAkOIRZJuQPq3LrL4mE8maq0nLfAb39xJsXSZu%2FJhr43Gs2ZjsPgv7XhBw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-08-20T17:05:17.735545+03:00", 
    "id": "17023e4f0b684642b0c13e1a5bbed326", 
    "dateModified": "2018-08-20T17:05:17.995900+03:00"
  }
}

