POST /api/2.4/tenders/21c028941810479099b6c304472fa513/documents?acc_token=ef5f4af395b94893ab1a36ee38398e9f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 339
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.openprocurement.org/get/9035207f9ba54138a05fbcb0e3d271dd?KeyID=26fd9873&Signature=VBf%2BDynjeH2J3bqPrDwrbZHHFe6%2Fxmyk%2FAKjQ%2FGXfgtXra1Sm4VozHy1%2Bkirs2h9a8MLnZOwIg6d4nn1BSHICw%3D%3D", 
    "title": "AwardCriteria.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/21c028941810479099b6c304472fa513/documents/0f33e002d3524589b4ecfd2c2fa52174

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "AwardCriteria.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/9035207f9ba54138a05fbcb0e3d271dd?KeyID=26fd9873&Signature=qoNAGuKX%2FVpJWN3brJUagH4FfldHDvE7T9XOqfI8ToJhQm7F%252B3ZVf4EPaHxfK3zIiuzPIQTnZs7VNNgHdyeGAw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-08-21T09:04:40.688726+03:00", 
    "id": "0f33e002d3524589b4ecfd2c2fa52174", 
    "dateModified": "2018-08-21T09:04:40.688747+03:00"
  }
}

