POST /api/2.4/tenders/bd895d3da2ba4b7da4e8909106eed4e4/documents?acc_token=1d0e92eeafee4e0282182542158f419a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 333
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.openprocurement.org/get/c6afd2ceb4f24264ac092fd8b4f875c1?KeyID=16711276&Signature=dxBM%2BvJyowbET799P7BwowqupUhIf7yFzEz9INq0Xzpg%2BtOaYREYr9hMIcyCgjRl3RBAiVIbhxEttbXzXOWkCA%3D%3D", 
    "title": "AwardCriteria.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/bd895d3da2ba4b7da4e8909106eed4e4/documents/5851d9f2d065433eab9a8d6a928cc478

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "AwardCriteria.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/c6afd2ceb4f24264ac092fd8b4f875c1?KeyID=16711276&Signature=fNVJXY3OWSVAaApFesCGr%252BQbr6ICH3LpqzCUhA96Ut2gYtrDebxoVbugqDtYO8rOTtY2qjdA9okddjHWA2EIAg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-08-20T17:05:13.881281+03:00", 
    "id": "5851d9f2d065433eab9a8d6a928cc478", 
    "dateModified": "2018-08-20T17:05:13.881300+03:00"
  }
}

