PATCH /api/2.4/tenders/d10e6f5566244a1191ba597b97b2f01c/awards/1e4a247831594cdd98f09921cdfaa260?acc_token=80477ee2aabf478d8508fb3f833987d3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "unsuccessful"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/d10e6f5566244a1191ba597b97b2f01c/awards/5c84cf03d5a34017b9101b1ae7e526f1

{
  "data": {
    "status": "unsuccessful", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "Cancellation_Reason.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/6743761cca8240969e69cfbe60043d36?KeyID=57a51152&Signature=v3xaC%2FT%252BzUy2tJpoOqOICV1YRsJAGPSae5xTZ%2FJsp%252Be9XCCRQtr7cpFoYNemyv7FpRrRE2lKwPvuovOaWH8%2FAw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-20T17:05:08.524417+03:00", 
        "id": "1a6efb07e1214657b8637def81085422", 
        "dateModified": "2018-08-20T17:05:08.524436+03:00"
      }
    ], 
    "complaintPeriod": {
      "startDate": "2018-08-20T17:05:08.305220+03:00", 
      "endDate": "2018-08-22T17:05:08.678837+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "bid_id": "ff9abedab4c2435282b220577d9d9439", 
    "value": {
      "currency": "UAH", 
      "amount": 469.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-08-20T17:05:08.686670+03:00", 
    "id": "1e4a247831594cdd98f09921cdfaa260"
  }
}

