GET /api/2.4/tenders/4734a19504774ff2a0f37c62ad04e3aa/awards HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "status": "pending", 
      "complaintPeriod": {
        "startDate": "2018-08-21T09:04:28.731046+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "49e2b1167a964a80b7853ba579dceb73", 
      "value": {
        "currency": "UAH", 
        "amount": 450.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-08-21T09:04:28.731034+03:00", 
      "id": "7be983dc8c914435bf4d9eac85691c0e"
    }
  ]
}

