PATCH /api/2.4/tenders/642d0d9c6f5d4bcaba32a998eb5ceb7a/awards/6a1e8963ef584fc5b02fc13836b6cd1f?acc_token=d795c096b96f4b3c8a9f977b0db7125e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "unsuccessful"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/642d0d9c6f5d4bcaba32a998eb5ceb7a/awards/1da9d718caf34315b12090ec213cb6d6

{
  "data": {
    "status": "unsuccessful", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "Unsuccessful_Reason.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/2d200e3291d0420ebb6ef7e1c7aa0dbe?KeyID=1268fedd&Signature=Viai2raleLL1Kk1mbLnRWRSMtk5flIrifsTLurubwNl%252B3k27oDMlJ0BLRy0jPMBymayP1sl3yrP1eyH2oEaWAg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-21T08:56:59.516464+03:00", 
        "id": "1f86582bb406448c9b60f2a1d02f844b", 
        "dateModified": "2018-08-21T08:56:59.516485+03:00"
      }
    ], 
    "complaintPeriod": {
      "startDate": "2018-08-21T08:56:59.309368+03:00", 
      "endDate": "2018-08-23T08:56:59.685359+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "bid_id": "94fdc09ac4f34d3aacfe77429ee07602", 
    "value": {
      "currency": "UAH", 
      "amount": 450.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-08-21T08:56:59.692104+03:00", 
    "id": "6a1e8963ef584fc5b02fc13836b6cd1f"
  }
}

