PATCH /api/2.4/tenders/afa62c501a20400f9ce1de70f14d5600/awards/5d96a0b16a8a44428a86085028d0b31d?acc_token=133bba2ff3fb4187a1fa13a3e86e6051 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "cancelled"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/afa62c501a20400f9ce1de70f14d5600/awards/fe19a961b9784cf48e21f3dc23ff9c9b

{
  "data": {
    "status": "cancelled", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "Unsuccessful_Reason.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/c918c5dd7a684535aa359fe43203dcfd?KeyID=647466d4&Signature=8QaZlNcj%2F6vF%2FQgN1f77o8cVLA%2FbO7HUq6I50eFvwmxad4FLOw63cPUnHKDryFOGh9NswZqfXxdABUtJ8PKDAg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-21T08:56:52.527059+03:00", 
        "id": "3cb7834357234f218c048f6dab8763ec", 
        "dateModified": "2018-08-21T08:56:52.527080+03:00"
      }
    ], 
    "complaintPeriod": {
      "startDate": "2018-08-21T08:56:52.330451+03:00", 
      "endDate": "2018-08-21T08:56:56.537339+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "bid_id": "5ba0253fb772410194d1bfb6731def17", 
    "value": {
      "currency": "UAH", 
      "amount": 450.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-08-21T08:56:56.547388+03:00", 
    "complaints": [
      {
        "status": "resolved", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "complaint_owner", 
            "title": "Complaint_Attachement.pdf", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/9b29baa8663240b6ac523c6d6f105e87?KeyID=647466d4&Signature=YECjdzcS%2FdzfFA3X15PCyPgmSxe3%2Fg%2FwbvnkufOiSvs1S4%2F1UyB22se%2Fbmxz944nQHHEX7ihmPAhpOBtbh3QAg%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2018-08-21T08:56:53.843827+03:00", 
            "id": "2d4fb429f5b74450ae0ddcd7b0f13b38", 
            "dateModified": "2018-08-21T08:56:53.843848+03:00"
          }
        ], 
        "description": "complaint description", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "resolutionType": "resolved", 
        "type": "claim", 
        "title": "complaint title", 
        "satisfied": true, 
        "tendererAction": "Виправлено неконкурентні умови", 
        "dateAnswered": "2018-08-21T08:56:54.543297+03:00", 
        "tendererActionDate": "2018-08-21T08:56:54.543315+03:00", 
        "dateSubmitted": "2018-08-21T08:56:54.025300+03:00", 
        "complaintID": "UA-2018-08-21-000001.5", 
        "date": "2018-08-21T08:56:54.731110+03:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "id": "7c4ef54ff5864ab9a13ecf68a5aceddb"
      }, 
      {
        "status": "resolved", 
        "description": "complaint description", 
        "title": "complaint title", 
        "resolutionType": "resolved", 
        "type": "claim", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "satisfied": false, 
        "dateAnswered": "2018-08-21T08:56:54.903442+03:00", 
        "dateSubmitted": "2018-08-21T08:56:54.193368+03:00", 
        "complaintID": "UA-2018-08-21-000001.6", 
        "date": "2018-08-21T08:56:55.090427+03:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "id": "a44f33957cd14b22b26fb809f8b84932"
      }, 
      {
        "status": "resolved", 
        "description": "complaint description", 
        "title": "complaint title", 
        "resolutionType": "resolved", 
        "type": "claim", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "satisfied": false, 
        "dateAnswered": "2018-08-21T08:56:55.448271+03:00", 
        "dateSubmitted": "2018-08-21T08:56:55.264281+03:00", 
        "complaintID": "UA-2018-08-21-000001.7", 
        "date": "2018-08-21T08:56:55.643481+03:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "id": "c5f36b94d1024c5db62467184691cbbb"
      }, 
      {
        "status": "resolved", 
        "description": "complaint description", 
        "title": "complaint title", 
        "resolutionType": "resolved", 
        "type": "claim", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "satisfied": false, 
        "dateAnswered": "2018-08-21T08:56:56.011167+03:00", 
        "dateSubmitted": "2018-08-21T08:56:55.818147+03:00", 
        "complaintID": "UA-2018-08-21-000001.8", 
        "date": "2018-08-21T08:56:56.212220+03:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "id": "b45b6c1baff348969732edcbe55d4362"
      }
    ], 
    "id": "5d96a0b16a8a44428a86085028d0b31d"
  }
}

