GET /api/2.4/tenders/afa62c501a20400f9ce1de70f14d5600/awards HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "status": "unsuccessful", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "tender_owner", 
          "title": "Unsuccessful_Reason.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/c918c5dd7a684535aa359fe43203dcfd?KeyID=647466d4&Signature=8QaZlNcj%2F6vF%2FQgN1f77o8cVLA%2FbO7HUq6I50eFvwmxad4FLOw63cPUnHKDryFOGh9NswZqfXxdABUtJ8PKDAg%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-08-21T08:56:52.527059+03:00", 
          "id": "3cb7834357234f218c048f6dab8763ec", 
          "dateModified": "2018-08-21T08:56:52.527080+03:00"
        }
      ], 
      "complaintPeriod": {
        "startDate": "2018-08-21T08:56:52.330451+03:00", 
        "endDate": "2018-08-23T08:56:52.699796+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "5ba0253fb772410194d1bfb6731def17", 
      "value": {
        "currency": "UAH", 
        "amount": 450.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-08-21T08:56:52.706777+03:00", 
      "complaints": [
        {
          "status": "resolved", 
          "documents": [
            {
              "hash": "md5:00000000000000000000000000000000", 
              "author": "complaint_owner", 
              "title": "Complaint_Attachement.pdf", 
              "url": "http://public.docs-sandbox.openprocurement.org/get/9b29baa8663240b6ac523c6d6f105e87?KeyID=647466d4&Signature=YECjdzcS%2FdzfFA3X15PCyPgmSxe3%2Fg%2FwbvnkufOiSvs1S4%2F1UyB22se%2Fbmxz944nQHHEX7ihmPAhpOBtbh3QAg%253D%253D", 
              "format": "application/pdf", 
              "documentOf": "tender", 
              "datePublished": "2018-08-21T08:56:53.843827+03:00", 
              "id": "2d4fb429f5b74450ae0ddcd7b0f13b38", 
              "dateModified": "2018-08-21T08:56:53.843848+03:00"
            }
          ], 
          "description": "complaint description", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "resolutionType": "resolved", 
          "type": "claim", 
          "title": "complaint title", 
          "satisfied": true, 
          "tendererAction": "Виправлено неконкурентні умови", 
          "dateAnswered": "2018-08-21T08:56:54.543297+03:00", 
          "tendererActionDate": "2018-08-21T08:56:54.543315+03:00", 
          "dateSubmitted": "2018-08-21T08:56:54.025300+03:00", 
          "complaintID": "UA-2018-08-21-000001.5", 
          "date": "2018-08-21T08:56:54.731110+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "7c4ef54ff5864ab9a13ecf68a5aceddb"
        }, 
        {
          "status": "resolved", 
          "description": "complaint description", 
          "title": "complaint title", 
          "resolutionType": "resolved", 
          "type": "claim", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "satisfied": false, 
          "dateAnswered": "2018-08-21T08:56:54.903442+03:00", 
          "dateSubmitted": "2018-08-21T08:56:54.193368+03:00", 
          "complaintID": "UA-2018-08-21-000001.6", 
          "date": "2018-08-21T08:56:55.090427+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "a44f33957cd14b22b26fb809f8b84932"
        }, 
        {
          "status": "resolved", 
          "description": "complaint description", 
          "title": "complaint title", 
          "resolutionType": "resolved", 
          "type": "claim", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "satisfied": false, 
          "dateAnswered": "2018-08-21T08:56:55.448271+03:00", 
          "dateSubmitted": "2018-08-21T08:56:55.264281+03:00", 
          "complaintID": "UA-2018-08-21-000001.7", 
          "date": "2018-08-21T08:56:55.643481+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "c5f36b94d1024c5db62467184691cbbb"
        }, 
        {
          "status": "resolved", 
          "description": "complaint description", 
          "title": "complaint title", 
          "resolutionType": "resolved", 
          "type": "claim", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "satisfied": false, 
          "dateAnswered": "2018-08-21T08:56:56.011167+03:00", 
          "dateSubmitted": "2018-08-21T08:56:55.818147+03:00", 
          "complaintID": "UA-2018-08-21-000001.8", 
          "date": "2018-08-21T08:56:56.212220+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "b45b6c1baff348969732edcbe55d4362"
        }
      ], 
      "id": "5d96a0b16a8a44428a86085028d0b31d"
    }, 
    {
      "status": "cancelled", 
      "complaintPeriod": {
        "startDate": "2018-08-21T08:56:52.700276+03:00", 
        "endDate": "2018-08-21T08:56:53.130491+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "66f745820b69463f836cbba05f2c327c", 
      "value": {
        "currency": "UAH", 
        "amount": 469.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-08-21T08:56:53.138315+03:00", 
      "id": "42a7f53ee680401ab8b980a29ce50f32"
    }, 
    {
      "status": "unsuccessful", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "tender_owner", 
          "title": "Cancellation_Reason.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/b1256f7b207f496bad6cd59e8a71ca91?KeyID=647466d4&Signature=VxEQD8v3fJrG4xqwjwzPVdWa4zzbqrZyBXLROFeDIMwhi2Fal8%2FV3WpHvhcwTrC55y315ajXBFNldHRou8mFDw%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-08-21T08:56:53.360010+03:00", 
          "id": "17e9bfef39514c7e999387563e2da4fa", 
          "dateModified": "2018-08-21T08:56:53.360031+03:00"
        }
      ], 
      "complaintPeriod": {
        "startDate": "2018-08-21T08:56:53.130934+03:00", 
        "endDate": "2018-08-23T08:56:53.517557+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "66f745820b69463f836cbba05f2c327c", 
      "value": {
        "currency": "UAH", 
        "amount": 469.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-08-21T08:56:53.525507+03:00", 
      "id": "0d01d47cf2c746c28a65a138d7e67532"
    }, 
    {
      "status": "pending", 
      "complaintPeriod": {
        "startDate": "2018-08-21T08:56:53.518026+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "d9023748b96348a2985b63a760456886", 
      "value": {
        "currency": "UAH", 
        "amount": 475.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-08-21T08:56:53.518014+03:00", 
      "id": "5884785c31954be3b1172e8f60e5cd77"
    }
  ]
}

