POST /api/2.4/tenders/a25c38a278e8492f9d00d36f50173873/awards/6494e90fe6cf4d37814131b0d9c1b356/documents?acc_token=cfabd4dff1fc4ded9da4865153457b04 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 339
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.openprocurement.org/get/06fb8a92b0e942e588cdeab4f8018a6a?KeyID=a97e205d&Signature=JP3UwabO8Z9pN%2FKTmDkPVW%2FrXt3EgxDGvi4e2mpkR29rOinwDKi07wpsuG20zcWDtWAbfKRUUAyVLC6ENvSmBg%3D%3D", 
    "title": "Cancellation_Reason.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/a25c38a278e8492f9d00d36f50173873/awards/6494e90fe6cf4d37814131b0d9c1b356/documents/9756b1fe71b14e2faf5dbe7f8a42e1bb

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "Cancellation_Reason.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/06fb8a92b0e942e588cdeab4f8018a6a?KeyID=a97e205d&Signature=CZjPcnKr940DEMmdDJ1nh3Ks%2FSsG2cniHP4K0FbZfGeWeKCMp0SaJxPxnhODgdAwA%252BvX6iMfR370WDpJikvDDg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-08-20T17:16:44.879080+03:00", 
    "id": "9756b1fe71b14e2faf5dbe7f8a42e1bb", 
    "dateModified": "2018-08-20T17:16:44.879098+03:00"
  }
}

