PATCH /api/2.4/tenders/a25c38a278e8492f9d00d36f50173873/awards/6494e90fe6cf4d37814131b0d9c1b356?acc_token=cfabd4dff1fc4ded9da4865153457b04 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "unsuccessful"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/a25c38a278e8492f9d00d36f50173873/awards/358b3830d0734ca898a016abec23136c

{
  "data": {
    "status": "unsuccessful", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "Cancellation_Reason.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/06fb8a92b0e942e588cdeab4f8018a6a?KeyID=a97e205d&Signature=CZjPcnKr940DEMmdDJ1nh3Ks%2FSsG2cniHP4K0FbZfGeWeKCMp0SaJxPxnhODgdAwA%252BvX6iMfR370WDpJikvDDg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-20T17:16:44.879080+03:00", 
        "id": "9756b1fe71b14e2faf5dbe7f8a42e1bb", 
        "dateModified": "2018-08-20T17:16:44.879098+03:00"
      }
    ], 
    "complaintPeriod": {
      "startDate": "2018-08-20T17:16:44.650186+03:00", 
      "endDate": "2018-08-22T17:16:45.035367+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "bid_id": "e6a44ecddf574d1a938a69a40694113f", 
    "value": {
      "currency": "UAH", 
      "amount": 469.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-08-20T17:16:45.043239+03:00", 
    "id": "6494e90fe6cf4d37814131b0d9c1b356"
  }
}

