PATCH /api/2.4/tenders/979269331ffb40a7896036f735600946/awards/9e8aa6d064514d31b946a9319b45aab7?acc_token=39ba2fa346eb4f78a15235102c682c72 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "unsuccessful"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/979269331ffb40a7896036f735600946/awards/19f1ce03d24e492c9db365c2648cd315

{
  "data": {
    "status": "unsuccessful", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "Unsuccessful_Reason.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/ac21a30ba37a49b397abd63a042f161d?KeyID=374c28b1&Signature=njmiNWW3gh0%252BD8ll%2F%252BYVroIz2vg1%252BItkldVP02LtLMiGKTT2PQcMGmh1TlUspHm%2FeEMroF1KyFJqML38rXmHBQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-21T09:04:34.521653+03:00", 
        "id": "f09520a82762497fa149a080c2985f8d", 
        "dateModified": "2018-08-21T09:04:34.521673+03:00"
      }
    ], 
    "complaintPeriod": {
      "startDate": "2018-08-21T09:04:34.327749+03:00", 
      "endDate": "2018-08-23T09:04:34.686277+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "bid_id": "af4a1706c83344f4938b44a8b70395f3", 
    "value": {
      "currency": "UAH", 
      "amount": 450.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-08-21T09:04:34.693024+03:00", 
    "id": "9e8aa6d064514d31b946a9319b45aab7"
  }
}

