GET /api/2.4/tenders/d10e6f5566244a1191ba597b97b2f01c/awards HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "status": "cancelled", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "tender_owner", 
          "title": "Unsuccessful_Reason.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/b1ad0627f1734b12bc2b47edcc06a1e0?KeyID=57a51152&Signature=HMYSHQ2sOKETNeAb2VxbiqCgETgcjEBjqG5N%2FPAKGHt7pTXXnz%252BmTpYxvT5eRnZYnijNY547uEBNbZTuCAusCQ%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-08-20T17:05:07.705719+03:00", 
          "id": "be0009f55c2a4a97b53888ee5e3a39d0", 
          "dateModified": "2018-08-20T17:05:07.705738+03:00"
        }
      ], 
      "complaintPeriod": {
        "startDate": "2018-08-20T17:05:07.503648+03:00", 
        "endDate": "2018-08-20T17:05:11.726320+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "3f627440ee474110a1f57856b56a23ef", 
      "value": {
        "currency": "UAH", 
        "amount": 450.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-08-20T17:05:11.736013+03:00", 
      "complaints": [
        {
          "status": "resolved", 
          "documents": [
            {
              "hash": "md5:00000000000000000000000000000000", 
              "author": "complaint_owner", 
              "title": "Complaint_Attachement.pdf", 
              "url": "http://public.docs-sandbox.openprocurement.org/get/62a22f1e64ab46bb9181b3a841eea092?KeyID=57a51152&Signature=xgs2BvShW8UQp7WLgrwJgr63n09g8de5ZAp5rF9JHwo%252B5jFENSI%2F6eUE06gwQoBG%252B6hTVdeADzZ%252BNlKWAlFcAQ%253D%253D", 
              "format": "application/pdf", 
              "documentOf": "tender", 
              "datePublished": "2018-08-20T17:05:08.992427+03:00", 
              "id": "f1470aa65cf84130adfe595c0e659b03", 
              "dateModified": "2018-08-20T17:05:08.992445+03:00"
            }
          ], 
          "description": "complaint description", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "resolutionType": "resolved", 
          "type": "claim", 
          "title": "complaint title", 
          "satisfied": true, 
          "tendererAction": "Виправлено неконкурентні умови", 
          "dateAnswered": "2018-08-20T17:05:09.701328+03:00", 
          "tendererActionDate": "2018-08-20T17:05:09.701347+03:00", 
          "dateSubmitted": "2018-08-20T17:05:09.172786+03:00", 
          "complaintID": "UA-2018-08-20-000001.5", 
          "date": "2018-08-20T17:05:09.891069+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "03a6a848b77943c09ba77210e4994fc9"
        }, 
        {
          "status": "resolved", 
          "description": "complaint description", 
          "title": "complaint title", 
          "resolutionType": "resolved", 
          "type": "claim", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "satisfied": false, 
          "dateAnswered": "2018-08-20T17:05:10.069487+03:00", 
          "dateSubmitted": "2018-08-20T17:05:09.344015+03:00", 
          "complaintID": "UA-2018-08-20-000001.6", 
          "date": "2018-08-20T17:05:10.256956+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "df83e80debfb4ff3bb9dd65776d83bc8"
        }, 
        {
          "status": "resolved", 
          "description": "complaint description", 
          "title": "complaint title", 
          "resolutionType": "resolved", 
          "type": "claim", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "satisfied": false, 
          "dateAnswered": "2018-08-20T17:05:10.617208+03:00", 
          "dateSubmitted": "2018-08-20T17:05:10.429747+03:00", 
          "complaintID": "UA-2018-08-20-000001.7", 
          "date": "2018-08-20T17:05:10.816285+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "ed66fb109faa4c4db0cae5fe825ede70"
        }, 
        {
          "status": "resolved", 
          "description": "complaint description", 
          "title": "complaint title", 
          "resolutionType": "resolved", 
          "type": "claim", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "satisfied": false, 
          "dateAnswered": "2018-08-20T17:05:11.197397+03:00", 
          "dateSubmitted": "2018-08-20T17:05:10.996056+03:00", 
          "complaintID": "UA-2018-08-20-000001.8", 
          "date": "2018-08-20T17:05:11.405819+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "4722b66646384381b50f411174b8d36d"
        }
      ], 
      "id": "c2383e46f62f4c9d9ed7e60dd7c76073"
    }, 
    {
      "status": "cancelled", 
      "complaintPeriod": {
        "startDate": "2018-08-20T17:05:07.873783+03:00", 
        "endDate": "2018-08-20T17:05:11.726320+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "ff9abedab4c2435282b220577d9d9439", 
      "value": {
        "currency": "UAH", 
        "amount": 469.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-08-20T17:05:08.312156+03:00", 
      "id": "4aac16afecfc472d8631521b04ea5ea8"
    }, 
    {
      "status": "cancelled", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "tender_owner", 
          "title": "Cancellation_Reason.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/6743761cca8240969e69cfbe60043d36?KeyID=57a51152&Signature=v3xaC%2FT%252BzUy2tJpoOqOICV1YRsJAGPSae5xTZ%2FJsp%252Be9XCCRQtr7cpFoYNemyv7FpRrRE2lKwPvuovOaWH8%2FAw%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-08-20T17:05:08.524417+03:00", 
          "id": "1a6efb07e1214657b8637def81085422", 
          "dateModified": "2018-08-20T17:05:08.524436+03:00"
        }
      ], 
      "complaintPeriod": {
        "startDate": "2018-08-20T17:05:08.305220+03:00", 
        "endDate": "2018-08-20T17:05:11.726320+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "ff9abedab4c2435282b220577d9d9439", 
      "value": {
        "currency": "UAH", 
        "amount": 469.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-08-20T17:05:11.736013+03:00", 
      "id": "1e4a247831594cdd98f09921cdfaa260"
    }, 
    {
      "status": "cancelled", 
      "complaintPeriod": {
        "startDate": "2018-08-20T17:05:08.679297+03:00", 
        "endDate": "2018-08-20T17:05:11.726320+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "fae93ea37bae4fcb8eeba02beebbe9d6", 
      "value": {
        "currency": "UAH", 
        "amount": 475.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-08-20T17:05:11.736013+03:00", 
      "id": "5c84cf03d5a34017b9101b1ae7e526f1"
    }, 
    {
      "status": "pending", 
      "complaintPeriod": {
        "startDate": "2018-08-20T17:05:11.726854+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "3f627440ee474110a1f57856b56a23ef", 
      "value": {
        "currency": "UAH", 
        "amount": 450.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-08-20T17:05:11.726843+03:00", 
      "id": "ccc087040e4f46029ba2ed647e6bbdb5"
    }
  ]
}

