GET /api/2.4/tenders/642d0d9c6f5d4bcaba32a998eb5ceb7a/awards HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "status": "pending", 
      "complaintPeriod": {
        "startDate": "2018-08-21T08:56:59.309368+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "94fdc09ac4f34d3aacfe77429ee07602", 
      "value": {
        "currency": "UAH", 
        "amount": 450.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-08-21T08:56:59.309357+03:00", 
      "id": "6a1e8963ef584fc5b02fc13836b6cd1f"
    }
  ]
}

