GET /api/2.4/tenders/979269331ffb40a7896036f735600946/awards HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "status": "cancelled", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "tender_owner", 
          "title": "Unsuccessful_Reason.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/ac21a30ba37a49b397abd63a042f161d?KeyID=374c28b1&Signature=njmiNWW3gh0%252BD8ll%2F%252BYVroIz2vg1%252BItkldVP02LtLMiGKTT2PQcMGmh1TlUspHm%2FeEMroF1KyFJqML38rXmHBQ%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-08-21T09:04:34.521653+03:00", 
          "id": "f09520a82762497fa149a080c2985f8d", 
          "dateModified": "2018-08-21T09:04:34.521673+03:00"
        }
      ], 
      "complaintPeriod": {
        "startDate": "2018-08-21T09:04:34.327749+03:00", 
        "endDate": "2018-08-21T09:04:38.566337+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "af4a1706c83344f4938b44a8b70395f3", 
      "value": {
        "currency": "UAH", 
        "amount": 450.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-08-21T09:04:38.577470+03:00", 
      "complaints": [
        {
          "status": "resolved", 
          "documents": [
            {
              "hash": "md5:00000000000000000000000000000000", 
              "author": "complaint_owner", 
              "title": "Complaint_Attachement.pdf", 
              "url": "http://public.docs-sandbox.openprocurement.org/get/bbd7d6e597be4ec38a540b9a2119edb1?KeyID=374c28b1&Signature=%252BdoL5OeW6WxYOInxI%2F9so2kUetmfqVxMbt83h8Bc4g6A1vZ%2FtoUMIzEmRApGmQZSc%2FQh7%252BZ9gV3jAFKdiLm5Dg%253D%253D", 
              "format": "application/pdf", 
              "documentOf": "tender", 
              "datePublished": "2018-08-21T09:04:35.829624+03:00", 
              "id": "71ab0b463a05448e889359dfcfd133d3", 
              "dateModified": "2018-08-21T09:04:35.829643+03:00"
            }
          ], 
          "description": "complaint description", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "resolutionType": "resolved", 
          "type": "claim", 
          "title": "complaint title", 
          "satisfied": true, 
          "tendererAction": "Виправлено неконкурентні умови", 
          "dateAnswered": "2018-08-21T09:04:36.530887+03:00", 
          "tendererActionDate": "2018-08-21T09:04:36.530906+03:00", 
          "dateSubmitted": "2018-08-21T09:04:36.007384+03:00", 
          "complaintID": "UA-2018-08-21-000001.5", 
          "date": "2018-08-21T09:04:36.720410+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "bb4d7ffdeacb4c20a48e16eff36b0360"
        }, 
        {
          "status": "resolved", 
          "description": "complaint description", 
          "title": "complaint title", 
          "resolutionType": "resolved", 
          "type": "claim", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "satisfied": false, 
          "dateAnswered": "2018-08-21T09:04:36.898132+03:00", 
          "dateSubmitted": "2018-08-21T09:04:36.176828+03:00", 
          "complaintID": "UA-2018-08-21-000001.6", 
          "date": "2018-08-21T09:04:37.087610+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "b20955e4e58f4d9482bf4a1e1e5930db"
        }, 
        {
          "status": "resolved", 
          "description": "complaint description", 
          "title": "complaint title", 
          "resolutionType": "resolved", 
          "type": "claim", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "satisfied": false, 
          "dateAnswered": "2018-08-21T09:04:37.440579+03:00", 
          "dateSubmitted": "2018-08-21T09:04:37.256304+03:00", 
          "complaintID": "UA-2018-08-21-000001.7", 
          "date": "2018-08-21T09:04:37.647834+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "5518b93795154ffabf8619de844a391e"
        }, 
        {
          "status": "resolved", 
          "description": "complaint description", 
          "title": "complaint title", 
          "resolutionType": "resolved", 
          "type": "claim", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "satisfied": false, 
          "dateAnswered": "2018-08-21T09:04:38.037360+03:00", 
          "dateSubmitted": "2018-08-21T09:04:37.833527+03:00", 
          "complaintID": "UA-2018-08-21-000001.8", 
          "date": "2018-08-21T09:04:38.240811+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "945390181d2a4e2e9a1a5cd17db69734"
        }
      ], 
      "id": "9e8aa6d064514d31b946a9319b45aab7"
    }, 
    {
      "status": "cancelled", 
      "complaintPeriod": {
        "startDate": "2018-08-21T09:04:34.686898+03:00", 
        "endDate": "2018-08-21T09:04:38.566337+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "08b0eef138a442c79672ba733fa15045", 
      "value": {
        "currency": "UAH", 
        "amount": 469.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-08-21T09:04:35.120138+03:00", 
      "id": "19f1ce03d24e492c9db365c2648cd315"
    }, 
    {
      "status": "cancelled", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "tender_owner", 
          "title": "Cancellation_Reason.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/ab7c11a6b7564db28e09bb6dabbf24e9?KeyID=374c28b1&Signature=%252BGNPJ5Xvv7ouAdEeEBUph0ohjX0gDT8CwLDZyJP%2FLwJKpFdOv0A41A8KPdPUsrMPWRO1K8%252BKuZ54y6gHraKLAw%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-08-21T09:04:35.350268+03:00", 
          "id": "480e1dc504d64cbba3d94c08221d5aa9", 
          "dateModified": "2018-08-21T09:04:35.350286+03:00"
        }
      ], 
      "complaintPeriod": {
        "startDate": "2018-08-21T09:04:35.113154+03:00", 
        "endDate": "2018-08-21T09:04:38.566337+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "08b0eef138a442c79672ba733fa15045", 
      "value": {
        "currency": "UAH", 
        "amount": 469.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-08-21T09:04:38.577470+03:00", 
      "id": "6f2f18454a7946478dfe0f85405a1880"
    }, 
    {
      "status": "cancelled", 
      "complaintPeriod": {
        "startDate": "2018-08-21T09:04:35.509013+03:00", 
        "endDate": "2018-08-21T09:04:38.566337+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "467d767ca65e4caea1325d5199fd6715", 
      "value": {
        "currency": "UAH", 
        "amount": 475.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-08-21T09:04:38.577470+03:00", 
      "id": "b446effc9f254833b0f31493f7b8e15e"
    }, 
    {
      "status": "pending", 
      "complaintPeriod": {
        "startDate": "2018-08-21T09:04:38.567140+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "af4a1706c83344f4938b44a8b70395f3", 
      "value": {
        "currency": "UAH", 
        "amount": 450.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-08-21T09:04:38.567127+03:00", 
      "id": "5a609a11d5b04cd8aac792fbe4556a92"
    }
  ]
}

