POST /api/2.4/tenders/4734a19504774ff2a0f37c62ad04e3aa/awards/7be983dc8c914435bf4d9eac85691c0e/documents?acc_token=daa2170eae2a49b2be35885f2399f257 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 339
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.openprocurement.org/get/32be0958be41447fa622d8dfb8d32b0e?KeyID=8fe199b3&Signature=PMZG72JWdUiHpX3%2FnSyu9Y3Wxv4ClLLzzCgY3jbPdu%2F0d7IdQevReyuAW8ESCk1vbC74GaEB1OYGjNK6jAC5Bw%3D%3D", 
    "title": "Unsuccessful_Reason.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/4734a19504774ff2a0f37c62ad04e3aa/awards/7be983dc8c914435bf4d9eac85691c0e/documents/699be3180ad346d79906b74aadd5a225

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "Unsuccessful_Reason.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/32be0958be41447fa622d8dfb8d32b0e?KeyID=8fe199b3&Signature=n2w0Sy%2FR2zNrBUh%2F6PrxgwF5R3SX7RDxZoLtMmX6pYIheONSo%2FE4rHv72kGt%2F%252BsRrOgpDRZmjIPcW%252BocyOspDg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-08-21T09:04:28.931715+03:00", 
    "id": "699be3180ad346d79906b74aadd5a225", 
    "dateModified": "2018-08-21T09:04:28.931736+03:00"
  }
}

