PATCH /api/2.4/tenders/a25c38a278e8492f9d00d36f50173873/awards/4bbe838bb5674dbc97edd0d7bdcd1ec6?acc_token=cfabd4dff1fc4ded9da4865153457b04 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "complaintPeriod": {
      "startDate": "2018-08-20T17:16:44.219112+03:00", 
      "endDate": "2018-08-22T17:16:44.425957+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "bid_id": "e6a44ecddf574d1a938a69a40694113f", 
    "value": {
      "currency": "UAH", 
      "amount": 469.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-08-20T17:16:44.431876+03:00", 
    "id": "4bbe838bb5674dbc97edd0d7bdcd1ec6"
  }
}

