PATCH /api/2.4/tenders/4734a19504774ff2a0f37c62ad04e3aa/awards/7be983dc8c914435bf4d9eac85691c0e?acc_token=daa2170eae2a49b2be35885f2399f257 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "cancelled"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/4734a19504774ff2a0f37c62ad04e3aa/awards/f4380400a4f845519f4ee67da2bbc1d0

{
  "data": {
    "status": "cancelled", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "Unsuccessful_Reason.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/32be0958be41447fa622d8dfb8d32b0e?KeyID=8fe199b3&Signature=n2w0Sy%2FR2zNrBUh%2F6PrxgwF5R3SX7RDxZoLtMmX6pYIheONSo%2FE4rHv72kGt%2F%252BsRrOgpDRZmjIPcW%252BocyOspDg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-21T09:04:28.931715+03:00", 
        "id": "699be3180ad346d79906b74aadd5a225", 
        "dateModified": "2018-08-21T09:04:28.931736+03:00"
      }
    ], 
    "complaintPeriod": {
      "startDate": "2018-08-21T09:04:28.731046+03:00", 
      "endDate": "2018-08-21T09:04:32.945029+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "bid_id": "49e2b1167a964a80b7853ba579dceb73", 
    "value": {
      "currency": "UAH", 
      "amount": 450.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-08-21T09:04:32.955513+03:00", 
    "complaints": [
      {
        "status": "resolved", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "complaint_owner", 
            "title": "Complaint_Attachement.pdf", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/6efda8f38e3b4883b6b71346bfddc19d?KeyID=8fe199b3&Signature=1Xsyx4V8dVPr%252BNwIZj%252B%2F1lsHl6w7Lw%252BfOxO1GpoEInLPfgNRqd7re2Ucr0BXEhXoHUnhfvBuc38gPpcEZ5H5Dw%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2018-08-21T09:04:30.234550+03:00", 
            "id": "2f2f198242e9437495950a308a049c0e", 
            "dateModified": "2018-08-21T09:04:30.234573+03:00"
          }
        ], 
        "description": "complaint description", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "resolutionType": "resolved", 
        "type": "claim", 
        "title": "complaint title", 
        "satisfied": true, 
        "tendererAction": "Виправлено неконкурентні умови", 
        "dateAnswered": "2018-08-21T09:04:30.947204+03:00", 
        "tendererActionDate": "2018-08-21T09:04:30.947223+03:00", 
        "dateSubmitted": "2018-08-21T09:04:30.421419+03:00", 
        "complaintID": "UA-2018-08-21-000001.5", 
        "date": "2018-08-21T09:04:31.147635+03:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "id": "b461b287eb8848f38dbedb3c3dda3180"
      }, 
      {
        "status": "resolved", 
        "description": "complaint description", 
        "title": "complaint title", 
        "resolutionType": "resolved", 
        "type": "claim", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "satisfied": false, 
        "dateAnswered": "2018-08-21T09:04:31.326112+03:00", 
        "dateSubmitted": "2018-08-21T09:04:30.592314+03:00", 
        "complaintID": "UA-2018-08-21-000001.6", 
        "date": "2018-08-21T09:04:31.517528+03:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "id": "3cc3903922eb4958a98add060abcb990"
      }, 
      {
        "status": "resolved", 
        "description": "complaint description", 
        "title": "complaint title", 
        "resolutionType": "resolved", 
        "type": "claim", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "satisfied": false, 
        "dateAnswered": "2018-08-21T09:04:31.880461+03:00", 
        "dateSubmitted": "2018-08-21T09:04:31.692092+03:00", 
        "complaintID": "UA-2018-08-21-000001.7", 
        "date": "2018-08-21T09:04:32.073157+03:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "id": "29180364cecf49148aad1fbfc9e0f5a4"
      }, 
      {
        "status": "resolved", 
        "description": "complaint description", 
        "title": "complaint title", 
        "resolutionType": "resolved", 
        "type": "claim", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "satisfied": false, 
        "dateAnswered": "2018-08-21T09:04:32.431080+03:00", 
        "dateSubmitted": "2018-08-21T09:04:32.247108+03:00", 
        "complaintID": "UA-2018-08-21-000001.8", 
        "date": "2018-08-21T09:04:32.627122+03:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "id": "a9fc417102334fc0bd3d31ab4f2a8586"
      }
    ], 
    "id": "7be983dc8c914435bf4d9eac85691c0e"
  }
}

