GET /api/2.4/tenders/4734a19504774ff2a0f37c62ad04e3aa/awards/49e2ef2fb8bc40209e3ef9235b95c730 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "complaintPeriod": {
      "startDate": "2018-08-21T09:04:29.104338+03:00", 
      "endDate": "2018-08-23T09:04:29.318330+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "bid_id": "cc3f91f80c6a41529e39dd9af93ee0a6", 
    "value": {
      "currency": "UAH", 
      "amount": 469.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-08-21T09:04:29.324194+03:00", 
    "id": "49e2ef2fb8bc40209e3ef9235b95c730"
  }
}

