GET /api/2.4/tenders/a25c38a278e8492f9d00d36f50173873/awards HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "status": "cancelled", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "tender_owner", 
          "title": "Unsuccessful_Reason.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/5caca2a7ae3943c7b6d06d8da8959c47?KeyID=a97e205d&Signature=822FvlBr5wy5rH1C6t%252BK0ixpMLBYRfOwHGPIIehFndqKBfMqF5liXtVaDmEIq%252BXUxhVUyRhYw22Kro9EzVS%252BAA%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-08-20T17:16:44.049734+03:00", 
          "id": "c30656db5ceb45b9b58ed007966142da", 
          "dateModified": "2018-08-20T17:16:44.049753+03:00"
        }
      ], 
      "complaintPeriod": {
        "startDate": "2018-08-20T17:16:43.855496+03:00", 
        "endDate": "2018-08-20T17:16:48.009635+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "7cb0d538004145bd9591b2d3d4c52521", 
      "value": {
        "currency": "UAH", 
        "amount": 450.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-08-20T17:16:48.019629+03:00", 
      "complaints": [
        {
          "status": "resolved", 
          "documents": [
            {
              "hash": "md5:00000000000000000000000000000000", 
              "author": "complaint_owner", 
              "title": "Complaint_Attachement.pdf", 
              "url": "http://public.docs-sandbox.openprocurement.org/get/998c702607a948fcb35f50aac865935e?KeyID=a97e205d&Signature=ysU2sMLxJDyt6bvpSy3R%2Fuhyb%252B80D8BXjd1f5weuQhVRP6twg9wSOzJs6V4%252BkWQ%252BZZC%2FjHJJJrW2kj83PDhuCA%253D%253D", 
              "format": "application/pdf", 
              "documentOf": "tender", 
              "datePublished": "2018-08-20T17:16:45.352163+03:00", 
              "id": "35a706d56bcf425b9e0a0aad17a87f8f", 
              "dateModified": "2018-08-20T17:16:45.352181+03:00"
            }
          ], 
          "description": "complaint description", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "resolutionType": "resolved", 
          "type": "claim", 
          "title": "complaint title", 
          "satisfied": true, 
          "tendererAction": "Виправлено неконкурентні умови", 
          "dateAnswered": "2018-08-20T17:16:46.046474+03:00", 
          "tendererActionDate": "2018-08-20T17:16:46.046491+03:00", 
          "dateSubmitted": "2018-08-20T17:16:45.529839+03:00", 
          "complaintID": "UA-2018-08-20-000001.5", 
          "date": "2018-08-20T17:16:46.230681+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "5c25c03fc1134f44bb0c159cd2471776"
        }, 
        {
          "status": "resolved", 
          "description": "complaint description", 
          "title": "complaint title", 
          "resolutionType": "resolved", 
          "type": "claim", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "satisfied": false, 
          "dateAnswered": "2018-08-20T17:16:46.404576+03:00", 
          "dateSubmitted": "2018-08-20T17:16:45.696587+03:00", 
          "complaintID": "UA-2018-08-20-000001.6", 
          "date": "2018-08-20T17:16:46.587813+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "b3935210ce83448ba69e526eeec949ef"
        }, 
        {
          "status": "resolved", 
          "description": "complaint description", 
          "title": "complaint title", 
          "resolutionType": "resolved", 
          "type": "claim", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "satisfied": false, 
          "dateAnswered": "2018-08-20T17:16:46.934715+03:00", 
          "dateSubmitted": "2018-08-20T17:16:46.755065+03:00", 
          "complaintID": "UA-2018-08-20-000001.7", 
          "date": "2018-08-20T17:16:47.133219+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "a5588beff2624f2693df5cb4fe7d511a"
        }, 
        {
          "status": "resolved", 
          "description": "complaint description", 
          "title": "complaint title", 
          "resolutionType": "resolved", 
          "type": "claim", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "satisfied": false, 
          "dateAnswered": "2018-08-20T17:16:47.493217+03:00", 
          "dateSubmitted": "2018-08-20T17:16:47.304906+03:00", 
          "complaintID": "UA-2018-08-20-000001.8", 
          "date": "2018-08-20T17:16:47.689884+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "712fc81a9c804b8fb5bcb782b558ea2c"
        }
      ], 
      "id": "8478b70080514e7d8a1c8426262e96e6"
    }, 
    {
      "status": "cancelled", 
      "complaintPeriod": {
        "startDate": "2018-08-20T17:16:44.219112+03:00", 
        "endDate": "2018-08-20T17:16:48.009635+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "e6a44ecddf574d1a938a69a40694113f", 
      "value": {
        "currency": "UAH", 
        "amount": 469.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-08-20T17:16:44.657465+03:00", 
      "id": "4bbe838bb5674dbc97edd0d7bdcd1ec6"
    }, 
    {
      "status": "cancelled", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "tender_owner", 
          "title": "Cancellation_Reason.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/06fb8a92b0e942e588cdeab4f8018a6a?KeyID=a97e205d&Signature=CZjPcnKr940DEMmdDJ1nh3Ks%2FSsG2cniHP4K0FbZfGeWeKCMp0SaJxPxnhODgdAwA%252BvX6iMfR370WDpJikvDDg%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-08-20T17:16:44.879080+03:00", 
          "id": "9756b1fe71b14e2faf5dbe7f8a42e1bb", 
          "dateModified": "2018-08-20T17:16:44.879098+03:00"
        }
      ], 
      "complaintPeriod": {
        "startDate": "2018-08-20T17:16:44.650186+03:00", 
        "endDate": "2018-08-20T17:16:48.009635+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "e6a44ecddf574d1a938a69a40694113f", 
      "value": {
        "currency": "UAH", 
        "amount": 469.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-08-20T17:16:48.019629+03:00", 
      "id": "6494e90fe6cf4d37814131b0d9c1b356"
    }, 
    {
      "status": "cancelled", 
      "complaintPeriod": {
        "startDate": "2018-08-20T17:16:45.035861+03:00", 
        "endDate": "2018-08-20T17:16:48.009635+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "780296fea6a44bc58fe866be8847a2f9", 
      "value": {
        "currency": "UAH", 
        "amount": 475.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-08-20T17:16:48.019629+03:00", 
      "id": "358b3830d0734ca898a016abec23136c"
    }, 
    {
      "status": "pending", 
      "complaintPeriod": {
        "startDate": "2018-08-20T17:16:48.010240+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "7cb0d538004145bd9591b2d3d4c52521", 
      "value": {
        "currency": "UAH", 
        "amount": 450.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-08-20T17:16:48.010230+03:00", 
      "id": "f77aa209f43c4ce3a3949feccc742388"
    }
  ]
}

