PATCH /api/2.4/tenders/d10e6f5566244a1191ba597b97b2f01c/awards/4aac16afecfc472d8631521b04ea5ea8?acc_token=80477ee2aabf478d8508fb3f833987d3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "complaintPeriod": {
      "startDate": "2018-08-20T17:05:07.873783+03:00", 
      "endDate": "2018-08-22T17:05:08.079621+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "bid_id": "ff9abedab4c2435282b220577d9d9439", 
    "value": {
      "currency": "UAH", 
      "amount": 469.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-08-20T17:05:08.085318+03:00", 
    "id": "4aac16afecfc472d8631521b04ea5ea8"
  }
}

